/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module gate(clk, rst, valid, a_vec, b_vec, acc, acc_valid);
  wire [31:0] _00_;
  wire [23:0] _01_;
  wire _02_;
  wire [31:0] _03_;
  wire [17:0] _04_;
  wire _05_;
  wire _06_;
  wire [23:0] _07_;
  wire _08_;
  wire [23:0] _09_;
  reg [31:0] a_reg;
  input [31:0] a_vec;
  wire [31:0] a_vec;
  output [23:0] acc;
  reg [23:0] acc;
  output acc_valid;
  reg acc_valid;
  reg [31:0] b_reg;
  input [31:0] b_vec;
  wire [31:0] b_vec;
  input clk;
  wire clk;
  wire [15:0] prod0;
  wire [15:0] prod1;
  wire [15:0] prod2;
  wire [15:0] prod3;
  input rst;
  wire rst;
  wire [17:0] sum;
  wire [16:0] sum01;
  wire [16:0] sum23;
  reg [17:0] sum_reg;
  input valid;
  wire valid;
  reg valid_reg;
  reg valid_reg2;
  assign sum01 = prod0 + prod1;
  assign sum23 = prod2 + prod3;
  assign sum = sum01 + sum23;
  assign _07_ = acc + { 6'h00, sum_reg };
  assign prod0 = a_reg[7:0] * b_reg[7:0];
  assign prod1 = a_reg[15:8] * b_reg[15:8];
  assign prod2 = a_reg[23:16] * b_reg[23:16];
  assign prod3 = a_reg[31:24] * b_reg[31:24];
  always @(posedge clk)
    acc <= _01_;
  always @(posedge clk)
    acc_valid <= _02_;
  always @(posedge clk)
    a_reg <= _00_;
  always @(posedge clk)
    b_reg <= _03_;
  always @(posedge clk)
    valid_reg <= _06_;
  always @(posedge clk)
    valid_reg2 <= _05_;
  always @(posedge clk)
    sum_reg <= _04_;
  assign _08_ = valid_reg2 ? 1'h1 : 1'h0;
  assign _02_ = rst ? 1'h0 : _08_;
  assign _09_ = valid_reg2 ? _07_ : acc;
  assign _01_ = rst ? 24'h000000 : _09_;
  assign _05_ = rst ? 1'h0 : valid_reg;
  assign _04_ = rst ? 18'h00000 : sum;
  assign _06_ = rst ? 1'h0 : valid;
  assign _03_ = rst ? 32'd0 : b_vec;
  assign _00_ = rst ? 32'd0 : a_vec;
endmodule

module gold(clk, rst, valid, a_vec, b_vec, acc, acc_valid);
  wire [31:0] _00_;
  wire [23:0] _01_;
  wire _02_;
  wire [31:0] _03_;
  wire _04_;
  wire [23:0] _05_;
  wire _06_;
  wire [23:0] _07_;
  reg [31:0] a_reg;
  input [31:0] a_vec;
  wire [31:0] a_vec;
  output [23:0] acc;
  reg [23:0] acc;
  output acc_valid;
  reg acc_valid;
  reg [31:0] b_reg;
  input [31:0] b_vec;
  wire [31:0] b_vec;
  input clk;
  wire clk;
  wire [15:0] prod0;
  wire [15:0] prod1;
  wire [15:0] prod2;
  wire [15:0] prod3;
  input rst;
  wire rst;
  wire [17:0] sum;
  wire [16:0] sum01;
  wire [16:0] sum23;
  input valid;
  wire valid;
  reg valid_reg;
  assign sum01 = prod0 + prod1;
  assign sum23 = prod2 + prod3;
  assign sum = sum01 + sum23;
  assign _05_ = acc + { 6'h00, sum };
  assign prod0 = a_reg[7:0] * b_reg[7:0];
  assign prod1 = a_reg[15:8] * b_reg[15:8];
  assign prod2 = a_reg[23:16] * b_reg[23:16];
  assign prod3 = a_reg[31:24] * b_reg[31:24];
  always @(posedge clk)
    acc <= _01_;
  always @(posedge clk)
    acc_valid <= _02_;
  always @(posedge clk)
    a_reg <= _00_;
  always @(posedge clk)
    b_reg <= _03_;
  always @(posedge clk)
    valid_reg <= _04_;
  assign _06_ = valid_reg ? 1'h1 : 1'h0;
  assign _02_ = rst ? 1'h0 : _06_;
  assign _07_ = valid_reg ? _05_ : acc;
  assign _01_ = rst ? 24'h000000 : _07_;
  assign _04_ = rst ? 1'h0 : valid;
  assign _03_ = rst ? 32'd0 : b_vec;
  assign _00_ = rst ? 32'd0 : a_vec;
endmodule
