/* Generated by Yosys 0.68+130 (git sha1 dd83bbad2-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module gate(clk_a, clk_b, rst, enable, count_a, count_b);
  input clk_a;
  wire clk_a;
  input clk_b;
  wire clk_b;
  input rst;
  wire rst;
  input enable;
  wire enable;
  output [7:0] count_a;
  reg [7:0] count_a;
  output [7:0] count_b;
  reg [7:0] count_b;
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire _04_;
  wire [7:0] _05_;
  wire _06_;
  wire [7:0] _07_;
  wire _08_;
  assign _02_ = count_a + 8'h01;
  always @(posedge clk_b)
    count_b <= _07_;
  always @(posedge clk_a)
    count_a <= _05_;
  assign _03_ = _04_ ? _02_ : count_a;
  assign _05_ = _06_ ? 8'h00 : _03_;
  assign _07_ = _08_ ? 8'h00 : count_a;
  assign _08_ = rst;
  assign _01_ = _07_;
  assign _04_ = enable;
  assign _06_ = rst;
  assign _00_ = _05_;
endmodule

module gold(clk_a, clk_b, rst, enable, count_a, count_b);
  input clk_a;
  wire clk_a;
  input clk_b;
  wire clk_b;
  input rst;
  wire rst;
  input enable;
  wire enable;
  output [7:0] count_a;
  reg [7:0] count_a;
  output [7:0] count_b;
  reg [7:0] count_b;
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  wire _05_;
  wire [7:0] _06_;
  wire _07_;
  wire [7:0] _08_;
  wire _09_;
  wire [7:0] _10_;
  wire _11_;
  reg [7:0] sync_stage1;
  assign _03_ = count_a + 8'h01;
  always @(posedge clk_b)
    count_b <= _04_;
  always @(posedge clk_b)
    sync_stage1 <= _06_;
  always @(posedge clk_a)
    count_a <= _10_;
  assign _04_ = _05_ ? 8'h00 : sync_stage1;
  assign _06_ = _07_ ? 8'h00 : count_a;
  assign _08_ = _09_ ? _03_ : count_a;
  assign _10_ = _11_ ? 8'h00 : _08_;
  assign _05_ = rst;
  assign _01_ = _04_;
  assign _07_ = rst;
  assign _02_ = _06_;
  assign _09_ = enable;
  assign _11_ = rst;
  assign _00_ = _10_;
endmodule
