/* Generated by Yosys 0.68+130 (git sha1 dd83bbad2-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module gate(clk, rst, red, green, yellow);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output red;
  wire red;
  output green;
  wire green;
  output yellow;
  wire yellow;
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire [1:0] _05_;
  wire _06_;
  wire [1:0] _07_;
  wire _08_;
  reg [1:0] state;
  assign _01_ = ! state;
  assign _02_ = state == 2'h1;
  assign _03_ = state == 2'h2;
  always @(posedge clk)
    state <= _05_;
  assign _04_ = ! state;
  assign _05_ = _06_ ? 2'h0 : _07_;
  function [1:0] _15_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _15_ = b[1:0];
      2'b1?:
        _15_ = b[3:2];
      default:
        _15_ = a;
    endcase
  endfunction
  assign _07_ = _15_(2'h0, 4'h6, { _04_, _08_ });
  assign _08_ = state == 2'h1;
  assign red = _01_;
  assign green = _02_;
  assign yellow = _03_;
  assign _06_ = rst;
  assign _00_ = _05_;
endmodule

module gold(clk, rst, red, green, yellow);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output red;
  wire red;
  output green;
  wire green;
  output yellow;
  wire yellow;
  wire [2:0] _00_;
  wire [2:0] _01_;
  wire _02_;
  wire _03_;
  wire [2:0] _04_;
  wire _05_;
  reg [2:0] state;
  always @(posedge clk)
    state <= _04_;
  function [2:0] _07_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _07_ = b[2:0];
      2'b1?:
        _07_ = b[5:3];
      default:
        _07_ = a;
    endcase
  endfunction
  assign _01_ = _07_(3'h1, 6'h14, { _03_, _02_ });
  assign _02_ = state == 3'h2;
  assign _03_ = state == 3'h1;
  assign _04_ = _05_ ? 3'h1 : _01_;
  assign red = state[0];
  assign green = state[1];
  assign yellow = state[2];
  assign _05_ = rst;
  assign _00_ = _04_;
endmodule
