/* Generated by Yosys 0.68+195 (git sha1 435977e97-dirty, Release, Clang /usr/bin/clang++ 21.1.8) */

module full_adder(a, b, cin, sum, cout);
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output sum;
  wire sum;
  output cout;
  wire cout;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  assign _00_ = a & b;
  assign _01_ = cin & _05_;
  assign _02_ = _00_ | _01_;
  assign _03_ = a ^ b;
  assign _04_ = _03_ ^ cin;
  assign _05_ = a ^ b;
  assign sum = _04_;
  assign cout = _02_;
endmodule

module gate(clk, rst, a, b, opcode, result, zero, carry);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input [2:0] opcode;
  wire [2:0] opcode;
  output [7:0] result;
  reg [7:0] result;
  output zero;
  reg zero;
  output carry;
  reg carry;
  wire _00_;
  wire _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire _04_;
  wire _05_;
  wire [7:0] _06_;
  wire [7:0] _07_;
  wire _08_;
  wire _09_;
  wire [7:0] _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire [7:0] _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire [7:0] _35_;
  wire [7:0] _36_;
  wire [7:0] _37_;
  wire _38_;
  wire [7:0] _39_;
  wire adder_carry_out;
  wire [7:0] adder_sum;
  wire [7:0] b_operand;
  wire [8:0] carry_chain;
  wire carry_next;
  wire [7:0] result_next;
  wire sub_mode;
  assign _07_ = a & b;
  assign _08_ = opcode == 3'h1;
  assign _09_ = ! result_next;
  assign _10_ = a | b;
  always @(posedge clk)
    result <= _15_;
  always @(posedge clk)
    zero <= _11_;
  always @(posedge clk)
    carry <= _13_;
  assign _11_ = _12_ ? 1'h1 : _09_;
  assign _13_ = _14_ ? 1'h0 : carry_next;
  assign _15_ = _16_ ? 8'h00 : result_next;
  function [0:0] _50_;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _50_ = b[0:0];
      8'b??????1?:
        _50_ = b[1:1];
      8'b?????1??:
        _50_ = b[2:2];
      8'b????1???:
        _50_ = b[3:3];
      8'b???1????:
        _50_ = b[4:4];
      8'b??1?????:
        _50_ = b[5:5];
      8'b?1??????:
        _50_ = b[6:6];
      8'b1???????:
        _50_ = b[7:7];
      default:
        _50_ = a;
    endcase
  endfunction
  assign _17_ = _50_(1'hx, { _38_, _38_, 3'h0, a[7], a[0], 1'h0 }, { _25_, _24_, _23_, _22_, _21_, _20_, _19_, _18_ });
  assign _18_ = opcode == 3'h7;
  assign _19_ = opcode == 3'h6;
  assign _20_ = opcode == 3'h5;
  assign _21_ = opcode == 3'h4;
  assign _22_ = opcode == 3'h3;
  assign _23_ = opcode == 3'h2;
  assign _24_ = opcode == 3'h1;
  assign _25_ = ! opcode;
  function [7:0] _59_;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _59_ = b[7:0];
      8'b??????1?:
        _59_ = b[15:8];
      8'b?????1??:
        _59_ = b[23:16];
      8'b????1???:
        _59_ = b[31:24];
      8'b???1????:
        _59_ = b[39:32];
      8'b??1?????:
        _59_ = b[47:40];
      8'b?1??????:
        _59_ = b[55:48];
      8'b1???????:
        _59_ = b[63:56];
      default:
        _59_ = a;
    endcase
  endfunction
  assign _26_ = _59_(8'hxx, { adder_sum, adder_sum, _07_, _10_, _39_, _35_, _36_, a }, { _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_ });
  assign _27_ = opcode == 3'h7;
  assign _28_ = opcode == 3'h6;
  assign _29_ = opcode == 3'h5;
  assign _30_ = opcode == 3'h4;
  assign _31_ = opcode == 3'h3;
  assign _32_ = opcode == 3'h2;
  assign _33_ = opcode == 3'h1;
  assign _34_ = ! opcode;
  assign _37_ = b ^ { sub_mode, sub_mode, sub_mode, sub_mode, sub_mode, sub_mode, sub_mode, sub_mode };
  assign _38_ = carry_chain[8] ^ sub_mode;
  assign _39_ = a ^ b;
  full_adder \ripple[0].fa  (
    .a(a[0]),
    .b(b_operand[0]),
    .cin(carry_chain[0]),
    .cout(carry_chain[1]),
    .sum(adder_sum[0])
  );
  full_adder \ripple[1].fa  (
    .a(a[1]),
    .b(b_operand[1]),
    .cin(carry_chain[1]),
    .cout(carry_chain[2]),
    .sum(adder_sum[1])
  );
  full_adder \ripple[2].fa  (
    .a(a[2]),
    .b(b_operand[2]),
    .cin(carry_chain[2]),
    .cout(carry_chain[3]),
    .sum(adder_sum[2])
  );
  full_adder \ripple[3].fa  (
    .a(a[3]),
    .b(b_operand[3]),
    .cin(carry_chain[3]),
    .cout(carry_chain[4]),
    .sum(adder_sum[3])
  );
  full_adder \ripple[4].fa  (
    .a(a[4]),
    .b(b_operand[4]),
    .cin(carry_chain[4]),
    .cout(carry_chain[5]),
    .sum(adder_sum[4])
  );
  full_adder \ripple[5].fa  (
    .a(a[5]),
    .b(b_operand[5]),
    .cin(carry_chain[5]),
    .cout(carry_chain[6]),
    .sum(adder_sum[5])
  );
  full_adder \ripple[6].fa  (
    .a(a[6]),
    .b(b_operand[6]),
    .cin(carry_chain[6]),
    .cout(carry_chain[7]),
    .sum(adder_sum[6])
  );
  full_adder \ripple[7].fa  (
    .a(a[7]),
    .b(b_operand[7]),
    .cin(carry_chain[7]),
    .cout(carry_chain[8]),
    .sum(adder_sum[7])
  );
  assign sub_mode = _08_;
  assign b_operand = _37_;
  assign carry_chain[0] = sub_mode;
  assign adder_carry_out = _38_;
  assign _01_ = _05_;
  assign _03_ = _06_;
  assign _12_ = rst;
  assign _04_ = _11_;
  assign _14_ = rst;
  assign _00_ = _13_;
  assign _16_ = rst;
  assign _02_ = _15_;
  assign _05_ = _17_;
  assign _06_ = _26_;
  assign result_next = _26_;
  assign carry_next = _17_;
  assign _35_ = { a[6:0], 1'h0 };
  assign _36_ = { 1'h0, a[7:1] };
endmodule

module gold(clk, rst, a, b, opcode, result, zero, carry);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input [2:0] opcode;
  wire [2:0] opcode;
  output [7:0] result;
  reg [7:0] result;
  output zero;
  reg zero;
  output carry;
  reg carry;
  wire _00_;
  wire _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire _04_;
  wire _05_;
  wire [7:0] _06_;
  wire [8:0] _07_;
  wire [7:0] _08_;
  wire _09_;
  wire [7:0] _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire [7:0] _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire [7:0] _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  wire _33_;
  wire _34_;
  wire [7:0] _35_;
  wire [7:0] _36_;
  wire [8:0] _37_;
  wire [7:0] _38_;
  wire carry_next;
  wire [7:0] result_next;
  assign _07_ = a + b;
  assign _08_ = a & b;
  assign _09_ = ! result_next;
  assign _10_ = a | b;
  always @(posedge clk)
    result <= _15_;
  always @(posedge clk)
    zero <= _11_;
  always @(posedge clk)
    carry <= _13_;
  assign _11_ = _12_ ? 1'h1 : _09_;
  assign _13_ = _14_ ? 1'h0 : carry_next;
  assign _15_ = _16_ ? 8'h00 : result_next;
  function [0:0] _49_;
    input [0:0] a;
    input [7:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _49_ = b[0:0];
      8'b??????1?:
        _49_ = b[1:1];
      8'b?????1??:
        _49_ = b[2:2];
      8'b????1???:
        _49_ = b[3:3];
      8'b???1????:
        _49_ = b[4:4];
      8'b??1?????:
        _49_ = b[5:5];
      8'b?1??????:
        _49_ = b[6:6];
      8'b1???????:
        _49_ = b[7:7];
      default:
        _49_ = a;
    endcase
  endfunction
  assign _17_ = _49_(1'hx, { _07_[8], _37_[8], 3'h0, a[7], a[0], 1'h0 }, { _25_, _24_, _23_, _22_, _21_, _20_, _19_, _18_ });
  assign _18_ = opcode == 3'h7;
  assign _19_ = opcode == 3'h6;
  assign _20_ = opcode == 3'h5;
  assign _21_ = opcode == 3'h4;
  assign _22_ = opcode == 3'h3;
  assign _23_ = opcode == 3'h2;
  assign _24_ = opcode == 3'h1;
  assign _25_ = ! opcode;
  function [7:0] _58_;
    input [7:0] a;
    input [63:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _58_ = b[7:0];
      8'b??????1?:
        _58_ = b[15:8];
      8'b?????1??:
        _58_ = b[23:16];
      8'b????1???:
        _58_ = b[31:24];
      8'b???1????:
        _58_ = b[39:32];
      8'b??1?????:
        _58_ = b[47:40];
      8'b?1??????:
        _58_ = b[55:48];
      8'b1???????:
        _58_ = b[63:56];
      default:
        _58_ = a;
    endcase
  endfunction
  assign _26_ = _58_(8'hxx, { _07_[7:0], _37_[7:0], _08_, _10_, _38_, _35_, _36_, a }, { _34_, _33_, _32_, _31_, _30_, _29_, _28_, _27_ });
  assign _27_ = opcode == 3'h7;
  assign _28_ = opcode == 3'h6;
  assign _29_ = opcode == 3'h5;
  assign _30_ = opcode == 3'h4;
  assign _31_ = opcode == 3'h3;
  assign _32_ = opcode == 3'h2;
  assign _33_ = opcode == 3'h1;
  assign _34_ = ! opcode;
  assign _37_ = a - b;
  assign _38_ = a ^ b;
  assign _01_ = _05_;
  assign _03_ = _06_;
  assign _12_ = rst;
  assign _04_ = _11_;
  assign _14_ = rst;
  assign _00_ = _13_;
  assign _16_ = rst;
  assign _02_ = _15_;
  assign _05_ = _17_;
  assign _06_ = _26_;
  assign result_next = _26_;
  assign carry_next = _17_;
  assign _35_ = { a[6:0], 1'h0 };
  assign _36_ = { 1'h0, a[7:1] };
endmodule
