/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module gate(clk, rst, count);
  wire [7:0] _0_;
  wire [7:0] _1_;
  wire [7:0] _2_;
  wire _3_;
  input clk;
  wire clk;
  output [7:0] count;
  reg [7:0] count;
  input rst;
  wire rst;
  assign _1_ = count + 1'h1;
  always @(posedge clk)
    count <= _2_;
  assign _2_ = _3_ ? 8'h00 : _1_;
  assign _3_ = rst;
  assign _0_ = _2_;
endmodule

module gold(clk, rst, count);
  wire [7:0] _0_;
  wire [7:0] _1_;
  wire _2_;
  wire [7:0] _3_;
  input clk;
  wire clk;
  output [7:0] count;
  reg [7:0] count;
  input rst;
  wire rst;
  assign _1_ = count + 1'h1;
  always @(posedge clk)
    count <= _3_;
  assign _3_ = _2_ ? 8'h00 : _1_;
  assign _2_ = rst;
  assign _0_ = _3_;
endmodule
