/* Generated by Yosys 0.68+post (git sha1 c12172fbae8af5e20f6fb52e3d4e92d56ed587b6, Release, AppleClang clang++ 21.0.0.21000101) */

(* top =  1  *)
(* src = "../designs/counter.v:1.1-14.10" *)
module counter(clk, rst, count);
  (* src = "../designs/counter.v:2.23-2.26" *)
  input clk;
  wire clk;
  (* src = "../designs/counter.v:3.23-3.26" *)
  input rst;
  wire rst;
  (* src = "../designs/counter.v:4.23-4.28" *)
  output [7:0] count;
  wire [7:0] count;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  (* force_downto = 32'd1 *)
  (* src = "../designs/counter.v:11.18-11.30|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _27_;
  INV_X1 _28_ (
    .A(rst),
    .ZN(_08_)
  );
  AND3_X1 _29_ (
    .A1(count[2]),
    .A2(count[1]),
    .A3(count[0]),
    .ZN(_09_)
  );
  AND4_X1 _30_ (
    .A1(count[2]),
    .A2(count[3]),
    .A3(count[1]),
    .A4(count[0]),
    .ZN(_10_)
  );
  AND3_X1 _31_ (
    .A1(count[5]),
    .A2(count[4]),
    .A3(_10_),
    .ZN(_11_)
  );
  OAI21_X1 _32_ (
    .A(_08_),
    .B1(_11_),
    .B2(count[6]),
    .ZN(_12_)
  );
  AOI21_X1 _33_ (
    .A(_12_),
    .B1(_11_),
    .B2(count[6]),
    .ZN(_00_)
  );
  AOI21_X1 _34_ (
    .A(count[5]),
    .B1(count[4]),
    .B2(_10_),
    .ZN(_13_)
  );
  NOR3_X1 _35_ (
    .A1(rst),
    .A2(_11_),
    .A3(_13_),
    .ZN(_01_)
  );
  OAI21_X1 _36_ (
    .A(_08_),
    .B1(_10_),
    .B2(count[4]),
    .ZN(_14_)
  );
  AOI21_X1 _37_ (
    .A(_14_),
    .B1(_10_),
    .B2(count[4]),
    .ZN(_02_)
  );
  OAI21_X1 _38_ (
    .A(_08_),
    .B1(_09_),
    .B2(count[3]),
    .ZN(_15_)
  );
  NOR2_X1 _39_ (
    .A1(_10_),
    .A2(_15_),
    .ZN(_03_)
  );
  AOI21_X1 _40_ (
    .A(count[2]),
    .B1(count[1]),
    .B2(count[0]),
    .ZN(_16_)
  );
  NOR3_X1 _41_ (
    .A1(rst),
    .A2(_09_),
    .A3(_16_),
    .ZN(_04_)
  );
  OAI21_X1 _42_ (
    .A(_08_),
    .B1(count[0]),
    .B2(count[1]),
    .ZN(_17_)
  );
  AOI21_X1 _43_ (
    .A(_17_),
    .B1(count[0]),
    .B2(count[1]),
    .ZN(_05_)
  );
  AND2_X1 _44_ (
    .A1(_08_),
    .A2(_27_[0]),
    .ZN(_06_)
  );
  AND3_X1 _45_ (
    .A1(count[7]),
    .A2(count[6]),
    .A3(_11_),
    .ZN(_18_)
  );
  AOI21_X1 _46_ (
    .A(count[7]),
    .B1(count[6]),
    .B2(_11_),
    .ZN(_19_)
  );
  NOR3_X1 _47_ (
    .A1(rst),
    .A2(_18_),
    .A3(_19_),
    .ZN(_07_)
  );
  (* src = "../designs/counter.v:7.1-12.4" *)
  DFF_X1 _48_ (
    .CK(clk),
    .D(_06_),
    .Q(count[0]),
    .QN(_27_[0])
  );
  (* src = "../designs/counter.v:7.1-12.4" *)
  DFF_X1 _49_ (
    .CK(clk),
    .D(_05_),
    .Q(count[1]),
    .QN(_21_)
  );
  (* src = "../designs/counter.v:7.1-12.4" *)
  DFF_X1 _50_ (
    .CK(clk),
    .D(_04_),
    .Q(count[2]),
    .QN(_22_)
  );
  (* src = "../designs/counter.v:7.1-12.4" *)
  DFF_X1 _51_ (
    .CK(clk),
    .D(_03_),
    .Q(count[3]),
    .QN(_23_)
  );
  (* src = "../designs/counter.v:7.1-12.4" *)
  DFF_X1 _52_ (
    .CK(clk),
    .D(_02_),
    .Q(count[4]),
    .QN(_24_)
  );
  (* src = "../designs/counter.v:7.1-12.4" *)
  DFF_X1 _53_ (
    .CK(clk),
    .D(_01_),
    .Q(count[5]),
    .QN(_25_)
  );
  (* src = "../designs/counter.v:7.1-12.4" *)
  DFF_X1 _54_ (
    .CK(clk),
    .D(_00_),
    .Q(count[6]),
    .QN(_26_)
  );
  (* src = "../designs/counter.v:7.1-12.4" *)
  DFF_X1 _55_ (
    .CK(clk),
    .D(_07_),
    .Q(count[7]),
    .QN(_20_)
  );
  assign _27_[7:1] = count[7:1];
endmodule
