/* Generated by Yosys 0.68+130 (git sha1 dd83bbad2-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module gate(clk, rst, start, op, a_vec, b_vec, result_vec, done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input start;
  wire start;
  input [2:0] op;
  wire [2:0] op;
  input [127:0] a_vec;
  wire [127:0] a_vec;
  input [127:0] b_vec;
  wire [127:0] b_vec;
  output [127:0] result_vec;
  reg [127:0] result_vec;
  output done;
  reg done;
  wire [127:0] _000_;
  wire [127:0] _001_;
  wire _002_;
  wire [15:0] _003_;
  wire [15:0] _004_;
  wire [15:0] _005_;
  wire [15:0] _006_;
  wire [15:0] _007_;
  wire [15:0] _008_;
  wire [15:0] _009_;
  wire [15:0] _010_;
  wire [2:0] _011_;
  wire [127:0] _012_;
  wire [1:0] _013_;
  wire [15:0] _014_;
  wire [15:0] _015_;
  wire [15:0] _016_;
  wire [15:0] _017_;
  wire [15:0] _018_;
  wire [15:0] _019_;
  wire [15:0] _020_;
  wire [15:0] _021_;
  wire [15:0] _022_;
  wire [15:0] _023_;
  wire [15:0] _024_;
  wire [15:0] _025_;
  wire [15:0] _026_;
  wire [15:0] _027_;
  wire [15:0] _028_;
  wire [15:0] _029_;
  wire [15:0] _030_;
  wire [15:0] _031_;
  wire [15:0] _032_;
  wire [15:0] _033_;
  wire [15:0] _034_;
  wire [15:0] _035_;
  wire [15:0] _036_;
  wire [15:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire [15:0] _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire [15:0] _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire [15:0] _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [15:0] _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [15:0] _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire [15:0] _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire [15:0] _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire [15:0] _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire [2:0] _126_;
  wire _127_;
  wire [2:0] _128_;
  wire _129_;
  wire [127:0] _130_;
  wire _131_;
  wire [127:0] _132_;
  wire _133_;
  wire [127:0] _134_;
  wire _135_;
  wire [127:0] _136_;
  wire _137_;
  wire [1:0] _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire [1:0] _142_;
  wire _143_;
  wire _144_;
  wire [1:0] _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire [127:0] _152_;
  wire _153_;
  wire [127:0] _154_;
  wire _155_;
  wire [15:0] _156_;
  wire [15:0] _157_;
  wire [15:0] _158_;
  wire [15:0] _159_;
  wire [15:0] _160_;
  wire [15:0] _161_;
  wire [15:0] _162_;
  wire [15:0] _163_;
  wire [15:0] _164_;
  wire [15:0] _165_;
  wire [15:0] _166_;
  wire [15:0] _167_;
  wire [15:0] _168_;
  wire [15:0] _169_;
  wire [15:0] _170_;
  wire [15:0] _171_;
  wire [15:0] _172_;
  wire [15:0] _173_;
  wire [15:0] _174_;
  wire [15:0] _175_;
  wire [15:0] _176_;
  wire [15:0] _177_;
  wire [15:0] _178_;
  wire [15:0] _179_;
  wire [15:0] _180_;
  wire [15:0] _181_;
  wire [15:0] _182_;
  wire [15:0] _183_;
  wire [15:0] _184_;
  wire [15:0] _185_;
  wire [15:0] _186_;
  wire [15:0] _187_;
  wire [15:0] _188_;
  wire [15:0] _189_;
  wire [15:0] _190_;
  wire [15:0] _191_;
  wire [15:0] _192_;
  wire [15:0] _193_;
  wire [15:0] _194_;
  wire [15:0] _195_;
  wire [15:0] _196_;
  wire [15:0] _197_;
  wire [15:0] _198_;
  wire [15:0] _199_;
  wire [15:0] _200_;
  wire [15:0] _201_;
  wire [15:0] _202_;
  wire [15:0] _203_;
  reg [127:0] a_reg;
  reg [127:0] b_reg;
  wire [127:0] lane_result;
  wire [15:0] \lanes[0].a_i ;
  wire [15:0] \lanes[0].b_i ;
  wire [15:0] \lanes[0].r_i ;
  wire [15:0] \lanes[1].a_i ;
  wire [15:0] \lanes[1].b_i ;
  wire [15:0] \lanes[1].r_i ;
  wire [15:0] \lanes[2].a_i ;
  wire [15:0] \lanes[2].b_i ;
  wire [15:0] \lanes[2].r_i ;
  wire [15:0] \lanes[3].a_i ;
  wire [15:0] \lanes[3].b_i ;
  wire [15:0] \lanes[3].r_i ;
  wire [15:0] \lanes[4].a_i ;
  wire [15:0] \lanes[4].b_i ;
  wire [15:0] \lanes[4].r_i ;
  wire [15:0] \lanes[5].a_i ;
  wire [15:0] \lanes[5].b_i ;
  wire [15:0] \lanes[5].r_i ;
  wire [15:0] \lanes[6].a_i ;
  wire [15:0] \lanes[6].b_i ;
  wire [15:0] \lanes[6].r_i ;
  wire [15:0] \lanes[7].a_i ;
  wire [15:0] \lanes[7].b_i ;
  wire [15:0] \lanes[7].r_i ;
  reg [2:0] op_reg;
  reg [1:0] state;
  assign _022_ = \lanes[1].a_i  + \lanes[1].b_i ;
  assign _023_ = \lanes[2].a_i  + \lanes[2].b_i ;
  assign _024_ = \lanes[3].a_i  + \lanes[3].b_i ;
  assign _025_ = \lanes[4].a_i  + \lanes[4].b_i ;
  assign _026_ = \lanes[5].a_i  + \lanes[5].b_i ;
  assign _027_ = \lanes[6].a_i  + \lanes[6].b_i ;
  assign _028_ = \lanes[7].a_i  + \lanes[7].b_i ;
  assign _029_ = \lanes[0].a_i  + \lanes[0].b_i ;
  assign _030_ = \lanes[0].a_i  & \lanes[0].b_i ;
  assign _031_ = \lanes[1].a_i  & \lanes[1].b_i ;
  assign _032_ = \lanes[2].a_i  & \lanes[2].b_i ;
  assign _033_ = \lanes[3].a_i  & \lanes[3].b_i ;
  assign _034_ = \lanes[4].a_i  & \lanes[4].b_i ;
  assign _035_ = \lanes[5].a_i  & \lanes[5].b_i ;
  assign _036_ = \lanes[6].a_i  & \lanes[6].b_i ;
  assign _037_ = \lanes[7].a_i  & \lanes[7].b_i ;
  assign _038_ = \lanes[1].a_i  > \lanes[1].b_i ;
  assign _039_ = \lanes[2].a_i  > \lanes[2].b_i ;
  assign _040_ = \lanes[3].a_i  > \lanes[3].b_i ;
  assign _041_ = \lanes[4].a_i  > \lanes[4].b_i ;
  assign _042_ = \lanes[5].a_i  > \lanes[5].b_i ;
  assign _043_ = \lanes[6].a_i  > \lanes[6].b_i ;
  assign _044_ = \lanes[7].a_i  > \lanes[7].b_i ;
  assign _045_ = \lanes[0].a_i  > \lanes[0].b_i ;
  assign _046_ = \lanes[1].a_i  < \lanes[1].b_i ;
  assign _047_ = \lanes[2].a_i  < \lanes[2].b_i ;
  assign _048_ = \lanes[3].a_i  < \lanes[3].b_i ;
  assign _049_ = \lanes[4].a_i  < \lanes[4].b_i ;
  assign _050_ = \lanes[5].a_i  < \lanes[5].b_i ;
  assign _051_ = \lanes[6].a_i  < \lanes[6].b_i ;
  assign _052_ = \lanes[7].a_i  < \lanes[7].b_i ;
  assign _053_ = \lanes[0].a_i  < \lanes[0].b_i ;
  always @(posedge clk)
    result_vec <= _154_;
  always @(posedge clk)
    done <= _150_;
  always @(posedge clk)
    state <= _145_;
  always @(posedge clk)
    a_reg <= _136_;
  always @(posedge clk)
    b_reg <= _132_;
  always @(posedge clk)
    op_reg <= _128_;
  function [15:0] _242_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _242_ = b[15:0];
      8'b??????1?:
        _242_ = b[31:16];
      8'b?????1??:
        _242_ = b[47:32];
      8'b????1???:
        _242_ = b[63:48];
      8'b???1????:
        _242_ = b[79:64];
      8'b??1?????:
        _242_ = b[95:80];
      8'b?1??????:
        _242_ = b[111:96];
      8'b1???????:
        _242_ = b[127:112];
      default:
        _242_ = a;
    endcase
  endfunction
  assign _054_ = _242_(16'hxxxx, { _028_, _178_, _186_, _194_, _162_, _170_, _037_, _203_ }, { _062_, _061_, _060_, _059_, _058_, _057_, _056_, _055_ });
  assign _055_ = op_reg == 3'h7;
  assign _056_ = op_reg == 3'h6;
  assign _057_ = op_reg == 3'h5;
  assign _058_ = op_reg == 3'h4;
  assign _059_ = op_reg == 3'h3;
  assign _060_ = op_reg == 3'h2;
  assign _061_ = op_reg == 3'h1;
  assign _062_ = ! op_reg;
  function [15:0] _251_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _251_ = b[15:0];
      8'b??????1?:
        _251_ = b[31:16];
      8'b?????1??:
        _251_ = b[47:32];
      8'b????1???:
        _251_ = b[63:48];
      8'b???1????:
        _251_ = b[79:64];
      8'b??1?????:
        _251_ = b[95:80];
      8'b?1??????:
        _251_ = b[111:96];
      8'b1???????:
        _251_ = b[127:112];
      default:
        _251_ = a;
    endcase
  endfunction
  assign _063_ = _251_(16'hxxxx, { _027_, _177_, _185_, _193_, _161_, _169_, _036_, _202_ }, { _071_, _070_, _069_, _068_, _067_, _066_, _065_, _064_ });
  assign _064_ = op_reg == 3'h7;
  assign _065_ = op_reg == 3'h6;
  assign _066_ = op_reg == 3'h5;
  assign _067_ = op_reg == 3'h4;
  assign _068_ = op_reg == 3'h3;
  assign _069_ = op_reg == 3'h2;
  assign _070_ = op_reg == 3'h1;
  assign _071_ = ! op_reg;
  function [15:0] _260_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _260_ = b[15:0];
      8'b??????1?:
        _260_ = b[31:16];
      8'b?????1??:
        _260_ = b[47:32];
      8'b????1???:
        _260_ = b[63:48];
      8'b???1????:
        _260_ = b[79:64];
      8'b??1?????:
        _260_ = b[95:80];
      8'b?1??????:
        _260_ = b[111:96];
      8'b1???????:
        _260_ = b[127:112];
      default:
        _260_ = a;
    endcase
  endfunction
  assign _072_ = _260_(16'hxxxx, { _026_, _176_, _184_, _192_, _160_, _168_, _035_, _201_ }, { _080_, _079_, _078_, _077_, _076_, _075_, _074_, _073_ });
  assign _073_ = op_reg == 3'h7;
  assign _074_ = op_reg == 3'h6;
  assign _075_ = op_reg == 3'h5;
  assign _076_ = op_reg == 3'h4;
  assign _077_ = op_reg == 3'h3;
  assign _078_ = op_reg == 3'h2;
  assign _079_ = op_reg == 3'h1;
  assign _080_ = ! op_reg;
  function [15:0] _269_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _269_ = b[15:0];
      8'b??????1?:
        _269_ = b[31:16];
      8'b?????1??:
        _269_ = b[47:32];
      8'b????1???:
        _269_ = b[63:48];
      8'b???1????:
        _269_ = b[79:64];
      8'b??1?????:
        _269_ = b[95:80];
      8'b?1??????:
        _269_ = b[111:96];
      8'b1???????:
        _269_ = b[127:112];
      default:
        _269_ = a;
    endcase
  endfunction
  assign _081_ = _269_(16'hxxxx, { _025_, _175_, _183_, _191_, _159_, _167_, _034_, _200_ }, { _089_, _088_, _087_, _086_, _085_, _084_, _083_, _082_ });
  assign _082_ = op_reg == 3'h7;
  assign _083_ = op_reg == 3'h6;
  assign _084_ = op_reg == 3'h5;
  assign _085_ = op_reg == 3'h4;
  assign _086_ = op_reg == 3'h3;
  assign _087_ = op_reg == 3'h2;
  assign _088_ = op_reg == 3'h1;
  assign _089_ = ! op_reg;
  function [15:0] _278_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _278_ = b[15:0];
      8'b??????1?:
        _278_ = b[31:16];
      8'b?????1??:
        _278_ = b[47:32];
      8'b????1???:
        _278_ = b[63:48];
      8'b???1????:
        _278_ = b[79:64];
      8'b??1?????:
        _278_ = b[95:80];
      8'b?1??????:
        _278_ = b[111:96];
      8'b1???????:
        _278_ = b[127:112];
      default:
        _278_ = a;
    endcase
  endfunction
  assign _090_ = _278_(16'hxxxx, { _024_, _174_, _182_, _190_, _158_, _166_, _033_, _199_ }, { _098_, _097_, _096_, _095_, _094_, _093_, _092_, _091_ });
  assign _091_ = op_reg == 3'h7;
  assign _092_ = op_reg == 3'h6;
  assign _093_ = op_reg == 3'h5;
  assign _094_ = op_reg == 3'h4;
  assign _095_ = op_reg == 3'h3;
  assign _096_ = op_reg == 3'h2;
  assign _097_ = op_reg == 3'h1;
  assign _098_ = ! op_reg;
  function [15:0] _287_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _287_ = b[15:0];
      8'b??????1?:
        _287_ = b[31:16];
      8'b?????1??:
        _287_ = b[47:32];
      8'b????1???:
        _287_ = b[63:48];
      8'b???1????:
        _287_ = b[79:64];
      8'b??1?????:
        _287_ = b[95:80];
      8'b?1??????:
        _287_ = b[111:96];
      8'b1???????:
        _287_ = b[127:112];
      default:
        _287_ = a;
    endcase
  endfunction
  assign _099_ = _287_(16'hxxxx, { _023_, _173_, _181_, _189_, _157_, _165_, _032_, _198_ }, { _107_, _106_, _105_, _104_, _103_, _102_, _101_, _100_ });
  assign _100_ = op_reg == 3'h7;
  assign _101_ = op_reg == 3'h6;
  assign _102_ = op_reg == 3'h5;
  assign _103_ = op_reg == 3'h4;
  assign _104_ = op_reg == 3'h3;
  assign _105_ = op_reg == 3'h2;
  assign _106_ = op_reg == 3'h1;
  assign _107_ = ! op_reg;
  function [15:0] _296_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _296_ = b[15:0];
      8'b??????1?:
        _296_ = b[31:16];
      8'b?????1??:
        _296_ = b[47:32];
      8'b????1???:
        _296_ = b[63:48];
      8'b???1????:
        _296_ = b[79:64];
      8'b??1?????:
        _296_ = b[95:80];
      8'b?1??????:
        _296_ = b[111:96];
      8'b1???????:
        _296_ = b[127:112];
      default:
        _296_ = a;
    endcase
  endfunction
  assign _108_ = _296_(16'hxxxx, { _022_, _172_, _180_, _188_, _156_, _164_, _031_, _197_ }, { _116_, _115_, _114_, _113_, _112_, _111_, _110_, _109_ });
  assign _109_ = op_reg == 3'h7;
  assign _110_ = op_reg == 3'h6;
  assign _111_ = op_reg == 3'h5;
  assign _112_ = op_reg == 3'h4;
  assign _113_ = op_reg == 3'h3;
  assign _114_ = op_reg == 3'h2;
  assign _115_ = op_reg == 3'h1;
  assign _116_ = ! op_reg;
  function [15:0] _305_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _305_ = b[15:0];
      8'b??????1?:
        _305_ = b[31:16];
      8'b?????1??:
        _305_ = b[47:32];
      8'b????1???:
        _305_ = b[63:48];
      8'b???1????:
        _305_ = b[79:64];
      8'b??1?????:
        _305_ = b[95:80];
      8'b?1??????:
        _305_ = b[111:96];
      8'b1???????:
        _305_ = b[127:112];
      default:
        _305_ = a;
    endcase
  endfunction
  assign _117_ = _305_(16'hxxxx, { _029_, _179_, _187_, _195_, _163_, _171_, _030_, _196_ }, { _125_, _124_, _123_, _122_, _121_, _120_, _119_, _118_ });
  assign _118_ = op_reg == 3'h7;
  assign _119_ = op_reg == 3'h6;
  assign _120_ = op_reg == 3'h5;
  assign _121_ = op_reg == 3'h4;
  assign _122_ = op_reg == 3'h3;
  assign _123_ = op_reg == 3'h2;
  assign _124_ = op_reg == 3'h1;
  assign _125_ = ! op_reg;
  assign _126_ = _127_ ? op : op_reg;
  assign _127_ = state == 2'h1;
  assign _128_ = _129_ ? 3'h0 : _126_;
  assign _130_ = _131_ ? b_vec : b_reg;
  assign _131_ = state == 2'h1;
  assign _132_ = _133_ ? 128'h00000000000000000000000000000000 : _130_;
  assign _134_ = _135_ ? a_vec : a_reg;
  assign _135_ = state == 2'h1;
  assign _136_ = _137_ ? 128'h00000000000000000000000000000000 : _134_;
  function [1:0] _323_;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        _323_ = b[1:0];
      4'b??1?:
        _323_ = b[3:2];
      4'b?1??:
        _323_ = b[5:4];
      4'b1???:
        _323_ = b[7:6];
      default:
        _323_ = a;
    endcase
  endfunction
  assign _138_ = _323_(state, { _142_, 6'h2c }, { _144_, _141_, _140_, _139_ });
  assign _139_ = state == 2'h3;
  assign _140_ = state == 2'h2;
  assign _141_ = state == 2'h1;
  assign _142_ = _143_ ? 2'h1 : state;
  assign _144_ = ! state;
  assign _145_ = _146_ ? 2'h0 : _138_;
  function [0:0] _330_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _330_ = b[0:0];
      2'b1?:
        _330_ = b[1:1];
      default:
        _330_ = a;
    endcase
  endfunction
  assign _147_ = _330_(done, 2'h1, { _149_, _148_ });
  assign _148_ = state == 2'h3;
  assign _149_ = ! state;
  assign _150_ = _151_ ? 1'h0 : _147_;
  assign _152_ = _153_ ? { \lanes[7].r_i , \lanes[6].r_i , \lanes[5].r_i , \lanes[4].r_i , \lanes[3].r_i , \lanes[2].r_i , \lanes[1].r_i , \lanes[0].r_i  } : result_vec;
  assign _153_ = state == 2'h2;
  assign _154_ = _155_ ? 128'h00000000000000000000000000000000 : _152_;
  assign _156_ = \lanes[1].a_i  << \lanes[1].b_i [3:0];
  assign _157_ = \lanes[2].a_i  << \lanes[2].b_i [3:0];
  assign _158_ = \lanes[3].a_i  << \lanes[3].b_i [3:0];
  assign _159_ = \lanes[4].a_i  << \lanes[4].b_i [3:0];
  assign _160_ = \lanes[5].a_i  << \lanes[5].b_i [3:0];
  assign _161_ = \lanes[6].a_i  << \lanes[6].b_i [3:0];
  assign _162_ = \lanes[7].a_i  << \lanes[7].b_i [3:0];
  assign _163_ = \lanes[0].a_i  << \lanes[0].b_i [3:0];
  assign _164_ = \lanes[1].a_i  >> \lanes[1].b_i [3:0];
  assign _165_ = \lanes[2].a_i  >> \lanes[2].b_i [3:0];
  assign _166_ = \lanes[3].a_i  >> \lanes[3].b_i [3:0];
  assign _167_ = \lanes[4].a_i  >> \lanes[4].b_i [3:0];
  assign _168_ = \lanes[5].a_i  >> \lanes[5].b_i [3:0];
  assign _169_ = \lanes[6].a_i  >> \lanes[6].b_i [3:0];
  assign _170_ = \lanes[7].a_i  >> \lanes[7].b_i [3:0];
  assign _171_ = \lanes[0].a_i  >> \lanes[0].b_i [3:0];
  assign _172_ = \lanes[1].a_i  - \lanes[1].b_i ;
  assign _173_ = \lanes[2].a_i  - \lanes[2].b_i ;
  assign _174_ = \lanes[3].a_i  - \lanes[3].b_i ;
  assign _175_ = \lanes[4].a_i  - \lanes[4].b_i ;
  assign _176_ = \lanes[5].a_i  - \lanes[5].b_i ;
  assign _177_ = \lanes[6].a_i  - \lanes[6].b_i ;
  assign _178_ = \lanes[7].a_i  - \lanes[7].b_i ;
  assign _179_ = \lanes[0].a_i  - \lanes[0].b_i ;
  assign _180_ = _046_ ? \lanes[1].a_i  : \lanes[1].b_i ;
  assign _181_ = _047_ ? \lanes[2].a_i  : \lanes[2].b_i ;
  assign _182_ = _048_ ? \lanes[3].a_i  : \lanes[3].b_i ;
  assign _183_ = _049_ ? \lanes[4].a_i  : \lanes[4].b_i ;
  assign _184_ = _050_ ? \lanes[5].a_i  : \lanes[5].b_i ;
  assign _185_ = _051_ ? \lanes[6].a_i  : \lanes[6].b_i ;
  assign _186_ = _052_ ? \lanes[7].a_i  : \lanes[7].b_i ;
  assign _187_ = _053_ ? \lanes[0].a_i  : \lanes[0].b_i ;
  assign _188_ = _038_ ? \lanes[1].a_i  : \lanes[1].b_i ;
  assign _189_ = _039_ ? \lanes[2].a_i  : \lanes[2].b_i ;
  assign _190_ = _040_ ? \lanes[3].a_i  : \lanes[3].b_i ;
  assign _191_ = _041_ ? \lanes[4].a_i  : \lanes[4].b_i ;
  assign _192_ = _042_ ? \lanes[5].a_i  : \lanes[5].b_i ;
  assign _193_ = _043_ ? \lanes[6].a_i  : \lanes[6].b_i ;
  assign _194_ = _044_ ? \lanes[7].a_i  : \lanes[7].b_i ;
  assign _195_ = _045_ ? \lanes[0].a_i  : \lanes[0].b_i ;
  assign _196_ = \lanes[0].a_i  ^ \lanes[0].b_i ;
  assign _197_ = \lanes[1].a_i  ^ \lanes[1].b_i ;
  assign _198_ = \lanes[2].a_i  ^ \lanes[2].b_i ;
  assign _199_ = \lanes[3].a_i  ^ \lanes[3].b_i ;
  assign _200_ = \lanes[4].a_i  ^ \lanes[4].b_i ;
  assign _201_ = \lanes[5].a_i  ^ \lanes[5].b_i ;
  assign _202_ = \lanes[6].a_i  ^ \lanes[6].b_i ;
  assign _203_ = \lanes[7].a_i  ^ \lanes[7].b_i ;
  assign \lanes[0].a_i  = a_reg[15:0];
  assign \lanes[0].b_i  = b_reg[15:0];
  assign lane_result[15:0] = \lanes[0].r_i ;
  assign \lanes[1].a_i  = a_reg[31:16];
  assign \lanes[1].b_i  = b_reg[31:16];
  assign lane_result[31:16] = \lanes[1].r_i ;
  assign \lanes[2].a_i  = a_reg[47:32];
  assign \lanes[2].b_i  = b_reg[47:32];
  assign lane_result[47:32] = \lanes[2].r_i ;
  assign \lanes[3].a_i  = a_reg[63:48];
  assign \lanes[3].b_i  = b_reg[63:48];
  assign lane_result[63:48] = \lanes[3].r_i ;
  assign \lanes[4].a_i  = a_reg[79:64];
  assign \lanes[4].b_i  = b_reg[79:64];
  assign lane_result[79:64] = \lanes[4].r_i ;
  assign \lanes[5].a_i  = a_reg[95:80];
  assign \lanes[5].b_i  = b_reg[95:80];
  assign lane_result[95:80] = \lanes[5].r_i ;
  assign \lanes[6].a_i  = a_reg[111:96];
  assign \lanes[6].b_i  = b_reg[111:96];
  assign lane_result[111:96] = \lanes[6].r_i ;
  assign \lanes[7].a_i  = a_reg[127:112];
  assign \lanes[7].b_i  = b_reg[127:112];
  assign lane_result[127:112] = \lanes[7].r_i ;
  assign _010_ = _021_;
  assign _009_ = _020_;
  assign _008_ = _019_;
  assign _007_ = _018_;
  assign _006_ = _017_;
  assign _005_ = _016_;
  assign _004_ = _015_;
  assign _003_ = _014_;
  assign _021_ = _054_;
  assign _020_ = _063_;
  assign _019_ = _072_;
  assign _018_ = _081_;
  assign _017_ = _090_;
  assign _016_ = _099_;
  assign _015_ = _108_;
  assign _014_ = _117_;
  assign _129_ = rst;
  assign _011_ = _128_;
  assign _133_ = rst;
  assign _001_ = _132_;
  assign _137_ = rst;
  assign _000_ = _136_;
  assign _143_ = start;
  assign _146_ = rst;
  assign _013_ = _145_;
  assign _151_ = rst;
  assign _002_ = _150_;
  assign _155_ = rst;
  assign _012_ = _154_;
  assign \lanes[7].r_i  = _054_;
  assign \lanes[6].r_i  = _063_;
  assign \lanes[5].r_i  = _072_;
  assign \lanes[4].r_i  = _081_;
  assign \lanes[3].r_i  = _090_;
  assign \lanes[2].r_i  = _099_;
  assign \lanes[1].r_i  = _108_;
  assign \lanes[0].r_i  = _117_;
endmodule

module gold(clk, rst, start, op, a_vec, b_vec, result_vec, done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input start;
  wire start;
  input [2:0] op;
  wire [2:0] op;
  input [127:0] a_vec;
  wire [127:0] a_vec;
  input [127:0] b_vec;
  wire [127:0] b_vec;
  output [127:0] result_vec;
  reg [127:0] result_vec;
  output done;
  reg done;
  wire [127:0] _000_;
  wire [127:0] _001_;
  wire _002_;
  wire [15:0] _003_;
  wire [15:0] _004_;
  wire [15:0] _005_;
  wire [15:0] _006_;
  wire [15:0] _007_;
  wire [15:0] _008_;
  wire [15:0] _009_;
  wire [15:0] _010_;
  wire [2:0] _011_;
  wire [127:0] _012_;
  wire [11:0] _013_;
  wire [15:0] _014_;
  wire [15:0] _015_;
  wire [15:0] _016_;
  wire [15:0] _017_;
  wire [15:0] _018_;
  wire [15:0] _019_;
  wire [15:0] _020_;
  wire [15:0] _021_;
  wire [15:0] _022_;
  wire [15:0] _023_;
  wire [15:0] _024_;
  wire [15:0] _025_;
  wire [15:0] _026_;
  wire [15:0] _027_;
  wire [15:0] _028_;
  wire [15:0] _029_;
  wire [15:0] _030_;
  wire [15:0] _031_;
  wire [15:0] _032_;
  wire [15:0] _033_;
  wire [15:0] _034_;
  wire [15:0] _035_;
  wire [15:0] _036_;
  wire [15:0] _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire [15:0] _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire [15:0] _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire [15:0] _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [15:0] _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire [15:0] _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire [15:0] _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire [15:0] _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire [15:0] _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire [2:0] _126_;
  wire _127_;
  wire [2:0] _128_;
  wire _129_;
  wire [127:0] _130_;
  wire _131_;
  wire [127:0] _132_;
  wire _133_;
  wire [127:0] _134_;
  wire _135_;
  wire [127:0] _136_;
  wire _137_;
  wire [11:0] _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire [11:0] _149_;
  wire _150_;
  wire _151_;
  wire [11:0] _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire [127:0] _159_;
  wire _160_;
  wire [127:0] _161_;
  wire _162_;
  wire [15:0] _163_;
  wire [15:0] _164_;
  wire [15:0] _165_;
  wire [15:0] _166_;
  wire [15:0] _167_;
  wire [15:0] _168_;
  wire [15:0] _169_;
  wire [15:0] _170_;
  wire [15:0] _171_;
  wire [15:0] _172_;
  wire [15:0] _173_;
  wire [15:0] _174_;
  wire [15:0] _175_;
  wire [15:0] _176_;
  wire [15:0] _177_;
  wire [15:0] _178_;
  wire [15:0] _179_;
  wire [15:0] _180_;
  wire [15:0] _181_;
  wire [15:0] _182_;
  wire [15:0] _183_;
  wire [15:0] _184_;
  wire [15:0] _185_;
  wire [15:0] _186_;
  wire [15:0] _187_;
  wire [15:0] _188_;
  wire [15:0] _189_;
  wire [15:0] _190_;
  wire [15:0] _191_;
  wire [15:0] _192_;
  wire [15:0] _193_;
  wire [15:0] _194_;
  wire [15:0] _195_;
  wire [15:0] _196_;
  wire [15:0] _197_;
  wire [15:0] _198_;
  wire [15:0] _199_;
  wire [15:0] _200_;
  wire [15:0] _201_;
  wire [15:0] _202_;
  wire [15:0] _203_;
  wire [15:0] _204_;
  wire [15:0] _205_;
  wire [15:0] _206_;
  wire [15:0] _207_;
  wire [15:0] _208_;
  wire [15:0] _209_;
  wire [15:0] _210_;
  reg [127:0] a_reg;
  reg [127:0] b_reg;
  wire [127:0] lane_result;
  wire [15:0] \lanes[0].a_i ;
  wire [15:0] \lanes[0].b_i ;
  wire [15:0] \lanes[0].r_i ;
  wire [15:0] \lanes[1].a_i ;
  wire [15:0] \lanes[1].b_i ;
  wire [15:0] \lanes[1].r_i ;
  wire [15:0] \lanes[2].a_i ;
  wire [15:0] \lanes[2].b_i ;
  wire [15:0] \lanes[2].r_i ;
  wire [15:0] \lanes[3].a_i ;
  wire [15:0] \lanes[3].b_i ;
  wire [15:0] \lanes[3].r_i ;
  wire [15:0] \lanes[4].a_i ;
  wire [15:0] \lanes[4].b_i ;
  wire [15:0] \lanes[4].r_i ;
  wire [15:0] \lanes[5].a_i ;
  wire [15:0] \lanes[5].b_i ;
  wire [15:0] \lanes[5].r_i ;
  wire [15:0] \lanes[6].a_i ;
  wire [15:0] \lanes[6].b_i ;
  wire [15:0] \lanes[6].r_i ;
  wire [15:0] \lanes[7].a_i ;
  wire [15:0] \lanes[7].b_i ;
  wire [15:0] \lanes[7].r_i ;
  reg [2:0] op_reg;
  reg [11:0] state;
  assign _022_ = \lanes[1].a_i  + \lanes[1].b_i ;
  assign _023_ = \lanes[2].a_i  + \lanes[2].b_i ;
  assign _025_ = \lanes[0].a_i  + \lanes[0].b_i ;
  assign _024_ = \lanes[3].a_i  + \lanes[3].b_i ;
  assign _026_ = \lanes[4].a_i  + \lanes[4].b_i ;
  assign _027_ = \lanes[5].a_i  + \lanes[5].b_i ;
  assign _028_ = \lanes[6].a_i  + \lanes[6].b_i ;
  assign _029_ = \lanes[7].a_i  + \lanes[7].b_i ;
  assign _030_ = \lanes[0].a_i  & \lanes[0].b_i ;
  assign _031_ = \lanes[1].a_i  & \lanes[1].b_i ;
  assign _032_ = \lanes[2].a_i  & \lanes[2].b_i ;
  assign _033_ = \lanes[3].a_i  & \lanes[3].b_i ;
  assign _034_ = \lanes[4].a_i  & \lanes[4].b_i ;
  assign _035_ = \lanes[5].a_i  & \lanes[5].b_i ;
  assign _036_ = \lanes[6].a_i  & \lanes[6].b_i ;
  assign _037_ = \lanes[7].a_i  & \lanes[7].b_i ;
  assign _038_ = \lanes[1].a_i  > \lanes[1].b_i ;
  assign _039_ = \lanes[2].a_i  > \lanes[2].b_i ;
  assign _040_ = \lanes[3].a_i  > \lanes[3].b_i ;
  assign _041_ = \lanes[4].a_i  > \lanes[4].b_i ;
  assign _042_ = \lanes[5].a_i  > \lanes[5].b_i ;
  assign _044_ = \lanes[0].a_i  > \lanes[0].b_i ;
  assign _043_ = \lanes[6].a_i  > \lanes[6].b_i ;
  assign _045_ = \lanes[7].a_i  > \lanes[7].b_i ;
  assign _046_ = \lanes[1].a_i  < \lanes[1].b_i ;
  assign _047_ = \lanes[2].a_i  < \lanes[2].b_i ;
  assign _048_ = \lanes[3].a_i  < \lanes[3].b_i ;
  assign _049_ = \lanes[4].a_i  < \lanes[4].b_i ;
  assign _050_ = \lanes[0].a_i  < \lanes[0].b_i ;
  assign _051_ = \lanes[5].a_i  < \lanes[5].b_i ;
  assign _052_ = \lanes[6].a_i  < \lanes[6].b_i ;
  assign _053_ = \lanes[7].a_i  < \lanes[7].b_i ;
  always @(posedge clk)
    result_vec <= _161_;
  always @(posedge clk)
    done <= _157_;
  always @(posedge clk)
    state <= _152_;
  always @(posedge clk)
    a_reg <= _136_;
  always @(posedge clk)
    b_reg <= _132_;
  always @(posedge clk)
    op_reg <= _128_;
  function [15:0] _249_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _249_ = b[15:0];
      8'b??????1?:
        _249_ = b[31:16];
      8'b?????1??:
        _249_ = b[47:32];
      8'b????1???:
        _249_ = b[63:48];
      8'b???1????:
        _249_ = b[79:64];
      8'b??1?????:
        _249_ = b[95:80];
      8'b?1??????:
        _249_ = b[111:96];
      8'b1???????:
        _249_ = b[127:112];
      default:
        _249_ = a;
    endcase
  endfunction
  assign _054_ = _249_(16'hxxxx, { _029_, _186_, _194_, _201_, _169_, _178_, _037_, _210_ }, { _062_, _061_, _060_, _059_, _058_, _057_, _056_, _055_ });
  assign _055_ = op_reg == 3'h7;
  assign _056_ = op_reg == 3'h6;
  assign _057_ = op_reg == 3'h5;
  assign _058_ = op_reg == 3'h4;
  assign _059_ = op_reg == 3'h3;
  assign _060_ = op_reg == 3'h2;
  assign _061_ = op_reg == 3'h1;
  assign _062_ = ! op_reg;
  function [15:0] _258_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _258_ = b[15:0];
      8'b??????1?:
        _258_ = b[31:16];
      8'b?????1??:
        _258_ = b[47:32];
      8'b????1???:
        _258_ = b[63:48];
      8'b???1????:
        _258_ = b[79:64];
      8'b??1?????:
        _258_ = b[95:80];
      8'b?1??????:
        _258_ = b[111:96];
      8'b1???????:
        _258_ = b[127:112];
      default:
        _258_ = a;
    endcase
  endfunction
  assign _063_ = _258_(16'hxxxx, { _028_, _185_, _193_, _200_, _168_, _177_, _036_, _209_ }, { _071_, _070_, _069_, _068_, _067_, _066_, _065_, _064_ });
  assign _064_ = op_reg == 3'h7;
  assign _065_ = op_reg == 3'h6;
  assign _066_ = op_reg == 3'h5;
  assign _067_ = op_reg == 3'h4;
  assign _068_ = op_reg == 3'h3;
  assign _069_ = op_reg == 3'h2;
  assign _070_ = op_reg == 3'h1;
  assign _071_ = ! op_reg;
  function [15:0] _267_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _267_ = b[15:0];
      8'b??????1?:
        _267_ = b[31:16];
      8'b?????1??:
        _267_ = b[47:32];
      8'b????1???:
        _267_ = b[63:48];
      8'b???1????:
        _267_ = b[79:64];
      8'b??1?????:
        _267_ = b[95:80];
      8'b?1??????:
        _267_ = b[111:96];
      8'b1???????:
        _267_ = b[127:112];
      default:
        _267_ = a;
    endcase
  endfunction
  assign _072_ = _267_(16'hxxxx, { _027_, _184_, _191_, _199_, _167_, _176_, _035_, _208_ }, { _080_, _079_, _078_, _077_, _076_, _075_, _074_, _073_ });
  assign _073_ = op_reg == 3'h7;
  assign _074_ = op_reg == 3'h6;
  assign _075_ = op_reg == 3'h5;
  assign _076_ = op_reg == 3'h4;
  assign _077_ = op_reg == 3'h3;
  assign _078_ = op_reg == 3'h2;
  assign _079_ = op_reg == 3'h1;
  assign _080_ = ! op_reg;
  function [15:0] _276_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _276_ = b[15:0];
      8'b??????1?:
        _276_ = b[31:16];
      8'b?????1??:
        _276_ = b[47:32];
      8'b????1???:
        _276_ = b[63:48];
      8'b???1????:
        _276_ = b[79:64];
      8'b??1?????:
        _276_ = b[95:80];
      8'b?1??????:
        _276_ = b[111:96];
      8'b1???????:
        _276_ = b[127:112];
      default:
        _276_ = a;
    endcase
  endfunction
  assign _081_ = _276_(16'hxxxx, { _026_, _182_, _190_, _198_, _166_, _175_, _034_, _207_ }, { _089_, _088_, _087_, _086_, _085_, _084_, _083_, _082_ });
  assign _082_ = op_reg == 3'h7;
  assign _083_ = op_reg == 3'h6;
  assign _084_ = op_reg == 3'h5;
  assign _085_ = op_reg == 3'h4;
  assign _086_ = op_reg == 3'h3;
  assign _087_ = op_reg == 3'h2;
  assign _088_ = op_reg == 3'h1;
  assign _089_ = ! op_reg;
  function [15:0] _285_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _285_ = b[15:0];
      8'b??????1?:
        _285_ = b[31:16];
      8'b?????1??:
        _285_ = b[47:32];
      8'b????1???:
        _285_ = b[63:48];
      8'b???1????:
        _285_ = b[79:64];
      8'b??1?????:
        _285_ = b[95:80];
      8'b?1??????:
        _285_ = b[111:96];
      8'b1???????:
        _285_ = b[127:112];
      default:
        _285_ = a;
    endcase
  endfunction
  assign _090_ = _285_(16'hxxxx, { _024_, _181_, _189_, _197_, _165_, _174_, _033_, _206_ }, { _098_, _097_, _096_, _095_, _094_, _093_, _092_, _091_ });
  assign _091_ = op_reg == 3'h7;
  assign _092_ = op_reg == 3'h6;
  assign _093_ = op_reg == 3'h5;
  assign _094_ = op_reg == 3'h4;
  assign _095_ = op_reg == 3'h3;
  assign _096_ = op_reg == 3'h2;
  assign _097_ = op_reg == 3'h1;
  assign _098_ = ! op_reg;
  function [15:0] _294_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _294_ = b[15:0];
      8'b??????1?:
        _294_ = b[31:16];
      8'b?????1??:
        _294_ = b[47:32];
      8'b????1???:
        _294_ = b[63:48];
      8'b???1????:
        _294_ = b[79:64];
      8'b??1?????:
        _294_ = b[95:80];
      8'b?1??????:
        _294_ = b[111:96];
      8'b1???????:
        _294_ = b[127:112];
      default:
        _294_ = a;
    endcase
  endfunction
  assign _099_ = _294_(16'hxxxx, { _023_, _180_, _188_, _196_, _164_, _173_, _032_, _205_ }, { _107_, _106_, _105_, _104_, _103_, _102_, _101_, _100_ });
  assign _100_ = op_reg == 3'h7;
  assign _101_ = op_reg == 3'h6;
  assign _102_ = op_reg == 3'h5;
  assign _103_ = op_reg == 3'h4;
  assign _104_ = op_reg == 3'h3;
  assign _105_ = op_reg == 3'h2;
  assign _106_ = op_reg == 3'h1;
  assign _107_ = ! op_reg;
  function [15:0] _303_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _303_ = b[15:0];
      8'b??????1?:
        _303_ = b[31:16];
      8'b?????1??:
        _303_ = b[47:32];
      8'b????1???:
        _303_ = b[63:48];
      8'b???1????:
        _303_ = b[79:64];
      8'b??1?????:
        _303_ = b[95:80];
      8'b?1??????:
        _303_ = b[111:96];
      8'b1???????:
        _303_ = b[127:112];
      default:
        _303_ = a;
    endcase
  endfunction
  assign _108_ = _303_(16'hxxxx, { _022_, _179_, _187_, _195_, _163_, _172_, _031_, _204_ }, { _116_, _115_, _114_, _113_, _112_, _111_, _110_, _109_ });
  assign _109_ = op_reg == 3'h7;
  assign _110_ = op_reg == 3'h6;
  assign _111_ = op_reg == 3'h5;
  assign _112_ = op_reg == 3'h4;
  assign _113_ = op_reg == 3'h3;
  assign _114_ = op_reg == 3'h2;
  assign _115_ = op_reg == 3'h1;
  assign _116_ = ! op_reg;
  function [15:0] _312_;
    input [15:0] a;
    input [127:0] b;
    input [7:0] s;
    casez (s) // synopsys parallel_case
      8'b???????1:
        _312_ = b[15:0];
      8'b??????1?:
        _312_ = b[31:16];
      8'b?????1??:
        _312_ = b[47:32];
      8'b????1???:
        _312_ = b[63:48];
      8'b???1????:
        _312_ = b[79:64];
      8'b??1?????:
        _312_ = b[95:80];
      8'b?1??????:
        _312_ = b[111:96];
      8'b1???????:
        _312_ = b[127:112];
      default:
        _312_ = a;
    endcase
  endfunction
  assign _117_ = _312_(16'hxxxx, { _025_, _183_, _192_, _202_, _170_, _171_, _030_, _203_ }, { _125_, _124_, _123_, _122_, _121_, _120_, _119_, _118_ });
  assign _118_ = op_reg == 3'h7;
  assign _119_ = op_reg == 3'h6;
  assign _120_ = op_reg == 3'h5;
  assign _121_ = op_reg == 3'h4;
  assign _122_ = op_reg == 3'h3;
  assign _123_ = op_reg == 3'h2;
  assign _124_ = op_reg == 3'h1;
  assign _125_ = ! op_reg;
  assign _126_ = _127_ ? op : op_reg;
  assign _127_ = state == 12'h002;
  assign _128_ = _129_ ? 3'h0 : _126_;
  assign _130_ = _131_ ? b_vec : b_reg;
  assign _131_ = state == 12'h002;
  assign _132_ = _133_ ? 128'h00000000000000000000000000000000 : _130_;
  assign _134_ = _135_ ? a_vec : a_reg;
  assign _135_ = state == 12'h002;
  assign _136_ = _137_ ? 128'h00000000000000000000000000000000 : _134_;
  function [11:0] _330_;
    input [11:0] a;
    input [131:0] b;
    input [10:0] s;
    casez (s) // synopsys parallel_case
      11'b??????????1:
        _330_ = b[11:0];
      11'b?????????1?:
        _330_ = b[23:12];
      11'b????????1??:
        _330_ = b[35:24];
      11'b???????1???:
        _330_ = b[47:36];
      11'b??????1????:
        _330_ = b[59:48];
      11'b?????1?????:
        _330_ = b[71:60];
      11'b????1??????:
        _330_ = b[83:72];
      11'b???1???????:
        _330_ = b[95:84];
      11'b??1????????:
        _330_ = b[107:96];
      11'b?1?????????:
        _330_ = b[119:108];
      11'b1??????????:
        _330_ = b[131:120];
      default:
        _330_ = a;
    endcase
  endfunction
  assign _138_ = _330_(12'h001, { _149_, 120'h004008010020040080100200400800 }, { _151_, _148_, _147_, _146_, _145_, _144_, _143_, _142_, _141_, _140_, _139_ });
  assign _139_ = state == 12'h400;
  assign _140_ = state == 12'h200;
  assign _141_ = state == 12'h100;
  assign _142_ = state == 12'h080;
  assign _143_ = state == 12'h040;
  assign _144_ = state == 12'h020;
  assign _145_ = state == 12'h010;
  assign _146_ = state == 12'h008;
  assign _147_ = state == 12'h004;
  assign _148_ = state == 12'h002;
  assign _149_ = _150_ ? 12'h002 : state;
  assign _151_ = state == 12'h001;
  assign _152_ = _153_ ? 12'h001 : _138_;
  function [0:0] _344_;
    input [0:0] a;
    input [1:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _344_ = b[0:0];
      2'b1?:
        _344_ = b[1:1];
      default:
        _344_ = a;
    endcase
  endfunction
  assign _154_ = _344_(done, 2'h1, { _156_, _155_ });
  assign _155_ = state == 12'h800;
  assign _156_ = state == 12'h001;
  assign _157_ = _158_ ? 1'h0 : _154_;
  assign _159_ = _160_ ? { \lanes[7].r_i , \lanes[6].r_i , \lanes[5].r_i , \lanes[4].r_i , \lanes[3].r_i , \lanes[2].r_i , \lanes[1].r_i , \lanes[0].r_i  } : result_vec;
  assign _160_ = state == 12'h200;
  assign _161_ = _162_ ? 128'h00000000000000000000000000000000 : _159_;
  assign _163_ = \lanes[1].a_i  << \lanes[1].b_i [3:0];
  assign _164_ = \lanes[2].a_i  << \lanes[2].b_i [3:0];
  assign _165_ = \lanes[3].a_i  << \lanes[3].b_i [3:0];
  assign _166_ = \lanes[4].a_i  << \lanes[4].b_i [3:0];
  assign _167_ = \lanes[5].a_i  << \lanes[5].b_i [3:0];
  assign _168_ = \lanes[6].a_i  << \lanes[6].b_i [3:0];
  assign _169_ = \lanes[7].a_i  << \lanes[7].b_i [3:0];
  assign _170_ = \lanes[0].a_i  << \lanes[0].b_i [3:0];
  assign _171_ = \lanes[0].a_i  >> \lanes[0].b_i [3:0];
  assign _172_ = \lanes[1].a_i  >> \lanes[1].b_i [3:0];
  assign _173_ = \lanes[2].a_i  >> \lanes[2].b_i [3:0];
  assign _174_ = \lanes[3].a_i  >> \lanes[3].b_i [3:0];
  assign _175_ = \lanes[4].a_i  >> \lanes[4].b_i [3:0];
  assign _176_ = \lanes[5].a_i  >> \lanes[5].b_i [3:0];
  assign _177_ = \lanes[6].a_i  >> \lanes[6].b_i [3:0];
  assign _178_ = \lanes[7].a_i  >> \lanes[7].b_i [3:0];
  assign _179_ = \lanes[1].a_i  - \lanes[1].b_i ;
  assign _180_ = \lanes[2].a_i  - \lanes[2].b_i ;
  assign _181_ = \lanes[3].a_i  - \lanes[3].b_i ;
  assign _183_ = \lanes[0].a_i  - \lanes[0].b_i ;
  assign _182_ = \lanes[4].a_i  - \lanes[4].b_i ;
  assign _184_ = \lanes[5].a_i  - \lanes[5].b_i ;
  assign _185_ = \lanes[6].a_i  - \lanes[6].b_i ;
  assign _186_ = \lanes[7].a_i  - \lanes[7].b_i ;
  assign _187_ = _046_ ? \lanes[1].a_i  : \lanes[1].b_i ;
  assign _188_ = _047_ ? \lanes[2].a_i  : \lanes[2].b_i ;
  assign _189_ = _048_ ? \lanes[3].a_i  : \lanes[3].b_i ;
  assign _190_ = _049_ ? \lanes[4].a_i  : \lanes[4].b_i ;
  assign _192_ = _050_ ? \lanes[0].a_i  : \lanes[0].b_i ;
  assign _191_ = _051_ ? \lanes[5].a_i  : \lanes[5].b_i ;
  assign _193_ = _052_ ? \lanes[6].a_i  : \lanes[6].b_i ;
  assign _194_ = _053_ ? \lanes[7].a_i  : \lanes[7].b_i ;
  assign _195_ = _038_ ? \lanes[1].a_i  : \lanes[1].b_i ;
  assign _196_ = _039_ ? \lanes[2].a_i  : \lanes[2].b_i ;
  assign _197_ = _040_ ? \lanes[3].a_i  : \lanes[3].b_i ;
  assign _198_ = _041_ ? \lanes[4].a_i  : \lanes[4].b_i ;
  assign _199_ = _042_ ? \lanes[5].a_i  : \lanes[5].b_i ;
  assign _200_ = _043_ ? \lanes[6].a_i  : \lanes[6].b_i ;
  assign _202_ = _044_ ? \lanes[0].a_i  : \lanes[0].b_i ;
  assign _201_ = _045_ ? \lanes[7].a_i  : \lanes[7].b_i ;
  assign _203_ = \lanes[0].a_i  ^ \lanes[0].b_i ;
  assign _204_ = \lanes[1].a_i  ^ \lanes[1].b_i ;
  assign _205_ = \lanes[2].a_i  ^ \lanes[2].b_i ;
  assign _206_ = \lanes[3].a_i  ^ \lanes[3].b_i ;
  assign _207_ = \lanes[4].a_i  ^ \lanes[4].b_i ;
  assign _208_ = \lanes[5].a_i  ^ \lanes[5].b_i ;
  assign _209_ = \lanes[6].a_i  ^ \lanes[6].b_i ;
  assign _210_ = \lanes[7].a_i  ^ \lanes[7].b_i ;
  assign \lanes[0].a_i  = a_reg[15:0];
  assign \lanes[0].b_i  = b_reg[15:0];
  assign lane_result[15:0] = \lanes[0].r_i ;
  assign \lanes[1].a_i  = a_reg[31:16];
  assign \lanes[1].b_i  = b_reg[31:16];
  assign lane_result[31:16] = \lanes[1].r_i ;
  assign \lanes[2].a_i  = a_reg[47:32];
  assign \lanes[2].b_i  = b_reg[47:32];
  assign lane_result[47:32] = \lanes[2].r_i ;
  assign \lanes[3].a_i  = a_reg[63:48];
  assign \lanes[3].b_i  = b_reg[63:48];
  assign lane_result[63:48] = \lanes[3].r_i ;
  assign \lanes[4].a_i  = a_reg[79:64];
  assign \lanes[4].b_i  = b_reg[79:64];
  assign lane_result[79:64] = \lanes[4].r_i ;
  assign \lanes[5].a_i  = a_reg[95:80];
  assign \lanes[5].b_i  = b_reg[95:80];
  assign lane_result[95:80] = \lanes[5].r_i ;
  assign \lanes[6].a_i  = a_reg[111:96];
  assign \lanes[6].b_i  = b_reg[111:96];
  assign lane_result[111:96] = \lanes[6].r_i ;
  assign \lanes[7].a_i  = a_reg[127:112];
  assign \lanes[7].b_i  = b_reg[127:112];
  assign lane_result[127:112] = \lanes[7].r_i ;
  assign _010_ = _021_;
  assign _009_ = _020_;
  assign _008_ = _019_;
  assign _007_ = _018_;
  assign _006_ = _017_;
  assign _005_ = _016_;
  assign _004_ = _015_;
  assign _003_ = _014_;
  assign _021_ = _054_;
  assign _020_ = _063_;
  assign _019_ = _072_;
  assign _018_ = _081_;
  assign _017_ = _090_;
  assign _016_ = _099_;
  assign _015_ = _108_;
  assign _014_ = _117_;
  assign _129_ = rst;
  assign _011_ = _128_;
  assign _133_ = rst;
  assign _001_ = _132_;
  assign _137_ = rst;
  assign _000_ = _136_;
  assign _150_ = start;
  assign _153_ = rst;
  assign _013_ = _152_;
  assign _158_ = rst;
  assign _002_ = _157_;
  assign _162_ = rst;
  assign _012_ = _161_;
  assign \lanes[7].r_i  = _054_;
  assign \lanes[6].r_i  = _063_;
  assign \lanes[5].r_i  = _072_;
  assign \lanes[4].r_i  = _081_;
  assign \lanes[3].r_i  = _090_;
  assign \lanes[2].r_i  = _099_;
  assign \lanes[1].r_i  = _108_;
  assign \lanes[0].r_i  = _117_;
endmodule
