/* Generated by Yosys 0.68+195 (git sha1 435977e97-dirty, Release, Clang /usr/bin/clang++ 21.1.8) */

module gate(clk, rst, in_valid, in_data, out_valid, out_data);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input in_valid;
  wire in_valid;
  input signed [7:0] in_data;
  wire signed [7:0] in_data;
  output out_valid;
  reg out_valid;
  output signed [18:0] out_data;
  reg signed [18:0] out_data;
  wire [18:0] _00_;
  wire _01_;
  wire [18:0] _02_;
  wire [18:0] _03_;
  wire [18:0] _04_;
  wire [18:0] _05_;
  wire [7:0] _06_;
  wire [7:0] _07_;
  wire [7:0] _08_;
  wire [7:0] _09_;
  wire [7:0] _10_;
  wire [7:0] _11_;
  wire _12_;
  wire _13_;
  wire [7:0] _14_;
  wire [7:0] _15_;
  wire [7:0] _16_;
  wire [7:0] _17_;
  wire [7:0] _18_;
  wire [7:0] _19_;
  wire signed [18:0] p0;
  wire signed [18:0] p1;
  wire signed [18:0] p2;
  wire signed [18:0] p3;
  reg signed [18:0] p3_r;
  wire signed [18:0] p4;
  reg signed [18:0] p4_r;
  wire signed [18:0] p5;
  reg signed [18:0] p5_r;
  wire signed [18:0] s1;
  wire signed [18:0] s2;
  reg signed [18:0] s2_r;
  wire signed [18:0] s3;
  wire signed [18:0] s4;
  wire signed [18:0] s5;
  reg signed [7:0] t0;
  reg signed [7:0] t1;
  reg signed [7:0] t2;
  reg signed [7:0] t3;
  reg signed [7:0] t4;
  reg signed [7:0] t5;
  reg vld;
  reg vld2;
  assign s1 = $signed(p0) + $signed(p1);
  assign s2 = $signed(s1) + $signed(p2);
  assign s3 = $signed(s2_r) + $signed(p3_r);
  assign s4 = $signed(s3) + $signed(p4_r);
  assign s5 = $signed(s4) + $signed(p5_r);
  assign p0 = $signed(t0) * $signed(8'h17);
  assign p1 = $signed(t1) * $signed(8'hd1);
  assign p2 = $signed(t2) * $signed(8'h51);
  assign p3 = $signed(t3) * $signed(8'h51);
  assign p4 = $signed(t4) * $signed(8'hd1);
  assign p5 = $signed(t5) * $signed(8'h17);
  always @(posedge clk)
    p5_r <= _04_;
  always @(posedge clk)
    p4_r <= _03_;
  always @(posedge clk)
    p3_r <= _02_;
  always @(posedge clk)
    s2_r <= _05_;
  always @(posedge clk)
    vld2 <= _12_;
  always @(posedge clk)
    out_valid <= _01_;
  always @(posedge clk)
    out_data <= _00_;
  always @(posedge clk)
    vld <= _13_;
  always @(posedge clk)
    t0 <= _06_;
  always @(posedge clk)
    t1 <= _07_;
  always @(posedge clk)
    t2 <= _08_;
  always @(posedge clk)
    t3 <= _09_;
  always @(posedge clk)
    t4 <= _10_;
  always @(posedge clk)
    t5 <= _11_;
  assign _01_ = rst ? 1'h0 : vld2;
  assign _00_ = rst ? 19'h00000 : s5;
  assign _12_ = rst ? 1'h0 : vld;
  assign _04_ = rst ? 19'h00000 : p5;
  assign _03_ = rst ? 19'h00000 : p4;
  assign _02_ = rst ? 19'h00000 : p3;
  assign _05_ = rst ? 19'h00000 : s2;
  assign _13_ = rst ? 1'h0 : in_valid;
  assign _14_ = in_valid ? t4 : t5;
  assign _11_ = rst ? 8'h00 : _14_;
  assign _15_ = in_valid ? t3 : t4;
  assign _10_ = rst ? 8'h00 : _15_;
  assign _16_ = in_valid ? t2 : t3;
  assign _09_ = rst ? 8'h00 : _16_;
  assign _17_ = in_valid ? t1 : t2;
  assign _08_ = rst ? 8'h00 : _17_;
  assign _18_ = in_valid ? t0 : t1;
  assign _07_ = rst ? 8'h00 : _18_;
  assign _19_ = in_valid ? in_data : t0;
  assign _06_ = rst ? 8'h00 : _19_;
endmodule

module gold(clk, rst, in_valid, in_data, out_valid, out_data);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input in_valid;
  wire in_valid;
  input signed [7:0] in_data;
  wire signed [7:0] in_data;
  output out_valid;
  reg out_valid;
  output signed [18:0] out_data;
  reg signed [18:0] out_data;
  wire [18:0] _00_;
  wire _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire [7:0] _04_;
  wire [7:0] _05_;
  wire [7:0] _06_;
  wire [7:0] _07_;
  wire _08_;
  wire [7:0] _09_;
  wire [7:0] _10_;
  wire [7:0] _11_;
  wire [7:0] _12_;
  wire [7:0] _13_;
  wire [7:0] _14_;
  wire signed [18:0] p0;
  wire signed [18:0] p1;
  wire signed [18:0] p2;
  wire signed [18:0] p3;
  wire signed [18:0] p4;
  wire signed [18:0] p5;
  wire signed [18:0] s1;
  wire signed [18:0] s2;
  wire signed [18:0] s3;
  wire signed [18:0] s4;
  wire signed [18:0] s5;
  reg signed [7:0] t0;
  reg signed [7:0] t1;
  reg signed [7:0] t2;
  reg signed [7:0] t3;
  reg signed [7:0] t4;
  reg signed [7:0] t5;
  reg vld;
  assign s1 = $signed(p0) + $signed(p1);
  assign s2 = $signed(s1) + $signed(p2);
  assign s3 = $signed(s2) + $signed(p3);
  assign s4 = $signed(s3) + $signed(p4);
  assign s5 = $signed(s4) + $signed(p5);
  assign p0 = $signed(t0) * $signed(8'h17);
  assign p1 = $signed(t1) * $signed(8'hd1);
  assign p2 = $signed(t2) * $signed(8'h51);
  assign p3 = $signed(t3) * $signed(8'h51);
  assign p4 = $signed(t4) * $signed(8'hd1);
  assign p5 = $signed(t5) * $signed(8'h17);
  always @(posedge clk)
    out_valid <= _01_;
  always @(posedge clk)
    out_data <= _00_;
  always @(posedge clk)
    vld <= _08_;
  always @(posedge clk)
    t0 <= _02_;
  always @(posedge clk)
    t1 <= _03_;
  always @(posedge clk)
    t2 <= _04_;
  always @(posedge clk)
    t3 <= _05_;
  always @(posedge clk)
    t4 <= _06_;
  always @(posedge clk)
    t5 <= _07_;
  assign _01_ = rst ? 1'h0 : vld;
  assign _00_ = rst ? 19'h00000 : s5;
  assign _08_ = rst ? 1'h0 : in_valid;
  assign _09_ = in_valid ? t4 : t5;
  assign _07_ = rst ? 8'h00 : _09_;
  assign _10_ = in_valid ? t3 : t4;
  assign _06_ = rst ? 8'h00 : _10_;
  assign _11_ = in_valid ? t2 : t3;
  assign _05_ = rst ? 8'h00 : _11_;
  assign _12_ = in_valid ? t1 : t2;
  assign _04_ = rst ? 8'h00 : _12_;
  assign _13_ = in_valid ? t0 : t1;
  assign _03_ = rst ? 8'h00 : _13_;
  assign _14_ = in_valid ? in_data : t0;
  assign _02_ = rst ? 8'h00 : _14_;
endmodule
