/* Generated by Yosys 0.68+130 (git sha1 dd83bbad2-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module gate(clk, rst, din, dout);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  reg [7:0] dout;
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  wire _03_;
  wire [7:0] _04_;
  wire _05_;
  wire [7:0] _06_;
  reg [7:0] stage1;
  assign _02_ = din + 8'h01;
  always @(posedge clk)
    dout <= _04_;
  always @(posedge clk)
    stage1 <= _06_;
  assign _04_ = _05_ ? 8'h00 : stage1;
  assign _06_ = _03_ ? 8'h00 : _02_;
  assign _05_ = rst;
  assign _00_ = _04_;
  assign _03_ = rst;
  assign _01_ = _06_;
endmodule

module gold(clk, rst, din, dout);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  reg [7:0] dout;
  wire [7:0] _0_;
  wire [7:0] _1_;
  wire [7:0] _2_;
  wire _3_;
  assign _1_ = din + 8'h01;
  always @(posedge clk)
    dout <= _2_;
  assign _2_ = _3_ ? 8'h00 : _1_;
  assign _3_ = rst;
  assign _0_ = _2_;
endmodule
