/* Generated by Yosys 0.68+195 (git sha1 435977e97-dirty, Release, Clang /usr/bin/clang++ 21.1.8) */

module traffic_light(clk, rst, red, green, yellow);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output red;
  wire red;
  output green;
  wire green;
  output yellow;
  wire yellow;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire [1:0] state;
  NOR2_X1 _04_ (
    .A1(_01_),
    .A2(state[1]),
    .ZN(green)
  );
  NOR2_X1 _05_ (
    .A1(state[1]),
    .A2(state[0]),
    .ZN(red)
  );
  NOR3_X1 _06_ (
    .A1(state[1]),
    .A2(state[0]),
    .A3(rst),
    .ZN(_02_)
  );
  NOR2_X1 _07_ (
    .A1(state[0]),
    .A2(_00_),
    .ZN(yellow)
  );
  NOR3_X1 _08_ (
    .A1(_01_),
    .A2(state[1]),
    .A3(rst),
    .ZN(_03_)
  );
  DFF_X1 _09_ (
    .CK(clk),
    .D(_03_),
    .Q(state[1]),
    .QN(_00_)
  );
  DFF_X1 _10_ (
    .CK(clk),
    .D(_02_),
    .Q(state[0]),
    .QN(_01_)
  );
endmodule
