/* Generated by Yosys 0.68+195 (git sha1 435977e97-dirty, Release, Clang /usr/bin/clang++ 21.1.8) */

module alu8(clk, rst, a, b, opcode, result, zero, carry);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input [2:0] opcode;
  wire [2:0] opcode;
  output [7:0] result;
  wire [7:0] result;
  output zero;
  wire zero;
  output carry;
  wire carry;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire [7:0] adder_sum;
  wire [7:0] b_operand;
  wire [8:0] carry_chain;
  wire sub_mode;
  INV_X1 _111_ (
    .A(opcode[2]),
    .ZN(_060_)
  );
  INV_X1 _112_ (
    .A(opcode[0]),
    .ZN(_061_)
  );
  INV_X1 _113_ (
    .A(a[7]),
    .ZN(_062_)
  );
  INV_X1 _114_ (
    .A(a[6]),
    .ZN(_063_)
  );
  INV_X1 _115_ (
    .A(a[5]),
    .ZN(_064_)
  );
  INV_X1 _116_ (
    .A(a[4]),
    .ZN(_065_)
  );
  INV_X1 _117_ (
    .A(a[3]),
    .ZN(_066_)
  );
  INV_X1 _118_ (
    .A(a[2]),
    .ZN(_067_)
  );
  INV_X1 _119_ (
    .A(a[1]),
    .ZN(_068_)
  );
  INV_X1 _120_ (
    .A(a[0]),
    .ZN(_069_)
  );
  INV_X1 _121_ (
    .A(rst),
    .ZN(_070_)
  );
  INV_X1 _122_ (
    .A(carry_chain[8]),
    .ZN(_071_)
  );
  NOR3_X1 _123_ (
    .A1(opcode[1]),
    .A2(opcode[2]),
    .A3(_061_),
    .ZN(sub_mode)
  );
  XOR2_X1 _124_ (
    .A(b[6]),
    .B(sub_mode),
    .Z(b_operand[6])
  );
  XOR2_X1 _125_ (
    .A(b[5]),
    .B(sub_mode),
    .Z(b_operand[5])
  );
  XOR2_X1 _126_ (
    .A(b[4]),
    .B(sub_mode),
    .Z(b_operand[4])
  );
  XOR2_X1 _127_ (
    .A(b[3]),
    .B(sub_mode),
    .Z(b_operand[3])
  );
  XOR2_X1 _128_ (
    .A(b[2]),
    .B(sub_mode),
    .Z(b_operand[2])
  );
  XOR2_X1 _129_ (
    .A(b[1]),
    .B(sub_mode),
    .Z(b_operand[1])
  );
  XOR2_X1 _130_ (
    .A(b[0]),
    .B(sub_mode),
    .Z(b_operand[0])
  );
  NOR2_X1 _131_ (
    .A1(a[6]),
    .A2(b[6]),
    .ZN(_072_)
  );
  NAND3_X1 _132_ (
    .A1(opcode[1]),
    .A2(_060_),
    .A3(opcode[0]),
    .ZN(_073_)
  );
  NAND2_X1 _133_ (
    .A1(a[6]),
    .A2(b[6]),
    .ZN(_074_)
  );
  NOR2_X1 _134_ (
    .A1(opcode[1]),
    .A2(opcode[0]),
    .ZN(_075_)
  );
  NAND3_X1 _135_ (
    .A1(opcode[2]),
    .A2(_074_),
    .A3(_075_),
    .ZN(_076_)
  );
  AOI21_X1 _136_ (
    .A(_072_),
    .B1(_073_),
    .B2(_076_),
    .ZN(_077_)
  );
  NOR2_X1 _137_ (
    .A1(opcode[1]),
    .A2(opcode[2]),
    .ZN(_078_)
  );
  NAND2_X1 _138_ (
    .A1(adder_sum[6]),
    .A2(_078_),
    .ZN(_079_)
  );
  AND3_X1 _139_ (
    .A1(opcode[1]),
    .A2(opcode[2]),
    .A3(opcode[0]),
    .ZN(_080_)
  );
  NAND2_X1 _140_ (
    .A1(a[6]),
    .A2(_080_),
    .ZN(_081_)
  );
  NAND3_X1 _141_ (
    .A1(opcode[1]),
    .A2(opcode[2]),
    .A3(_061_),
    .ZN(_082_)
  );
  NAND3_X1 _142_ (
    .A1(opcode[1]),
    .A2(_060_),
    .A3(_061_),
    .ZN(_083_)
  );
  OR3_X1 _143_ (
    .A1(opcode[1]),
    .A2(_060_),
    .A3(_061_),
    .ZN(_084_)
  );
  OAI22_X1 _144_ (
    .A1(_074_),
    .A2(_083_),
    .B1(_084_),
    .B2(_064_),
    .ZN(_085_)
  );
  OAI211_X1 _145_ (
    .A(_079_),
    .B(_081_),
    .C1(_082_),
    .C2(_062_),
    .ZN(_086_)
  );
  NOR3_X1 _146_ (
    .A1(_077_),
    .A2(_085_),
    .A3(_086_),
    .ZN(_087_)
  );
  NOR2_X1 _147_ (
    .A1(rst),
    .A2(_087_),
    .ZN(_000_)
  );
  OR2_X1 _148_ (
    .A1(a[5]),
    .A2(b[5]),
    .ZN(_088_)
  );
  AND2_X1 _149_ (
    .A1(a[5]),
    .A2(b[5]),
    .ZN(_089_)
  );
  OR4_X1 _150_ (
    .A1(opcode[1]),
    .A2(_060_),
    .A3(opcode[0]),
    .A4(_089_),
    .ZN(_090_)
  );
  NAND2_X1 _151_ (
    .A1(a[5]),
    .A2(_080_),
    .ZN(_091_)
  );
  OAI211_X1 _152_ (
    .A(opcode[1]),
    .B(_060_),
    .C1(opcode[0]),
    .C2(_089_),
    .ZN(_092_)
  );
  NAND3_X1 _153_ (
    .A1(_090_),
    .A2(_091_),
    .A3(_092_),
    .ZN(_093_)
  );
  OAI22_X1 _154_ (
    .A1(_063_),
    .A2(_082_),
    .B1(_084_),
    .B2(_065_),
    .ZN(_094_)
  );
  AOI221_X1 _155_ (
    .A(_094_),
    .B1(_093_),
    .B2(_088_),
    .C1(adder_sum[5]),
    .C2(_078_),
    .ZN(_095_)
  );
  NOR2_X1 _156_ (
    .A1(rst),
    .A2(_095_),
    .ZN(_001_)
  );
  NOR2_X1 _157_ (
    .A1(a[4]),
    .A2(b[4]),
    .ZN(_096_)
  );
  NAND2_X1 _158_ (
    .A1(a[4]),
    .A2(b[4]),
    .ZN(_097_)
  );
  NAND3_X1 _159_ (
    .A1(opcode[2]),
    .A2(_075_),
    .A3(_097_),
    .ZN(_098_)
  );
  AOI21_X1 _160_ (
    .A(_096_),
    .B1(_098_),
    .B2(_073_),
    .ZN(_099_)
  );
  NAND2_X1 _161_ (
    .A1(adder_sum[4]),
    .A2(_078_),
    .ZN(_100_)
  );
  NAND2_X1 _162_ (
    .A1(a[4]),
    .A2(_080_),
    .ZN(_010_)
  );
  OAI21_X1 _163_ (
    .A(_010_),
    .B1(_097_),
    .B2(_083_),
    .ZN(_011_)
  );
  OAI221_X1 _164_ (
    .A(_100_),
    .B1(_084_),
    .B2(_066_),
    .C1(_064_),
    .C2(_082_),
    .ZN(_012_)
  );
  NOR3_X1 _165_ (
    .A1(_099_),
    .A2(_011_),
    .A3(_012_),
    .ZN(_013_)
  );
  NOR2_X1 _166_ (
    .A1(rst),
    .A2(_013_),
    .ZN(_002_)
  );
  NOR2_X1 _167_ (
    .A1(a[3]),
    .A2(b[3]),
    .ZN(_014_)
  );
  NAND2_X1 _168_ (
    .A1(a[3]),
    .A2(b[3]),
    .ZN(_015_)
  );
  NAND3_X1 _169_ (
    .A1(opcode[2]),
    .A2(_075_),
    .A3(_015_),
    .ZN(_016_)
  );
  AOI21_X1 _170_ (
    .A(_014_),
    .B1(_016_),
    .B2(_073_),
    .ZN(_017_)
  );
  NAND2_X1 _171_ (
    .A1(adder_sum[3]),
    .A2(_078_),
    .ZN(_018_)
  );
  NAND2_X1 _172_ (
    .A1(a[3]),
    .A2(_080_),
    .ZN(_019_)
  );
  OAI21_X1 _173_ (
    .A(_019_),
    .B1(_015_),
    .B2(_083_),
    .ZN(_020_)
  );
  OAI221_X1 _174_ (
    .A(_018_),
    .B1(_084_),
    .B2(_067_),
    .C1(_065_),
    .C2(_082_),
    .ZN(_021_)
  );
  NOR3_X1 _175_ (
    .A1(_017_),
    .A2(_020_),
    .A3(_021_),
    .ZN(_022_)
  );
  NOR2_X1 _176_ (
    .A1(rst),
    .A2(_022_),
    .ZN(_003_)
  );
  NOR2_X1 _177_ (
    .A1(a[2]),
    .A2(b[2]),
    .ZN(_023_)
  );
  NAND2_X1 _178_ (
    .A1(a[2]),
    .A2(b[2]),
    .ZN(_024_)
  );
  NAND3_X1 _179_ (
    .A1(opcode[2]),
    .A2(_075_),
    .A3(_024_),
    .ZN(_025_)
  );
  AOI21_X1 _180_ (
    .A(_023_),
    .B1(_025_),
    .B2(_073_),
    .ZN(_026_)
  );
  NAND2_X1 _181_ (
    .A1(adder_sum[2]),
    .A2(_078_),
    .ZN(_027_)
  );
  NAND2_X1 _182_ (
    .A1(a[2]),
    .A2(_080_),
    .ZN(_028_)
  );
  OAI21_X1 _183_ (
    .A(_028_),
    .B1(_024_),
    .B2(_083_),
    .ZN(_029_)
  );
  OAI221_X1 _184_ (
    .A(_027_),
    .B1(_084_),
    .B2(_068_),
    .C1(_066_),
    .C2(_082_),
    .ZN(_030_)
  );
  NOR3_X1 _185_ (
    .A1(_026_),
    .A2(_029_),
    .A3(_030_),
    .ZN(_031_)
  );
  NOR2_X1 _186_ (
    .A1(rst),
    .A2(_031_),
    .ZN(_004_)
  );
  OR2_X1 _187_ (
    .A1(a[1]),
    .A2(b[1]),
    .ZN(_032_)
  );
  AND2_X1 _188_ (
    .A1(a[1]),
    .A2(b[1]),
    .ZN(_033_)
  );
  OR4_X1 _189_ (
    .A1(opcode[1]),
    .A2(_060_),
    .A3(opcode[0]),
    .A4(_033_),
    .ZN(_034_)
  );
  NAND2_X1 _190_ (
    .A1(a[1]),
    .A2(_080_),
    .ZN(_035_)
  );
  OAI211_X1 _191_ (
    .A(opcode[1]),
    .B(_060_),
    .C1(opcode[0]),
    .C2(_033_),
    .ZN(_036_)
  );
  NAND3_X1 _192_ (
    .A1(_034_),
    .A2(_035_),
    .A3(_036_),
    .ZN(_037_)
  );
  OAI22_X1 _193_ (
    .A1(_067_),
    .A2(_082_),
    .B1(_084_),
    .B2(_069_),
    .ZN(_038_)
  );
  AOI221_X1 _194_ (
    .A(_038_),
    .B1(_037_),
    .B2(_032_),
    .C1(adder_sum[1]),
    .C2(_078_),
    .ZN(_039_)
  );
  NOR2_X1 _195_ (
    .A1(rst),
    .A2(_039_),
    .ZN(_005_)
  );
  NOR2_X1 _196_ (
    .A1(a[0]),
    .A2(b[0]),
    .ZN(_040_)
  );
  NAND2_X1 _197_ (
    .A1(a[0]),
    .A2(b[0]),
    .ZN(_041_)
  );
  NAND3_X1 _198_ (
    .A1(opcode[2]),
    .A2(_075_),
    .A3(_041_),
    .ZN(_042_)
  );
  AOI21_X1 _199_ (
    .A(_040_),
    .B1(_042_),
    .B2(_073_),
    .ZN(_043_)
  );
  NAND2_X1 _200_ (
    .A1(a[0]),
    .A2(_080_),
    .ZN(_044_)
  );
  OAI221_X1 _201_ (
    .A(_044_),
    .B1(_041_),
    .B2(_083_),
    .C1(_068_),
    .C2(_082_),
    .ZN(_045_)
  );
  AOI211_X1 _202_ (
    .A(_043_),
    .B(_045_),
    .C1(adder_sum[0]),
    .C2(_078_),
    .ZN(_046_)
  );
  NOR2_X1 _203_ (
    .A1(rst),
    .A2(_046_),
    .ZN(_006_)
  );
  NOR2_X1 _204_ (
    .A1(a[7]),
    .A2(b[7]),
    .ZN(_047_)
  );
  NAND2_X1 _205_ (
    .A1(a[7]),
    .A2(b[7]),
    .ZN(_048_)
  );
  NAND3_X1 _206_ (
    .A1(opcode[2]),
    .A2(_075_),
    .A3(_048_),
    .ZN(_049_)
  );
  AOI21_X1 _207_ (
    .A(_047_),
    .B1(_049_),
    .B2(_073_),
    .ZN(_050_)
  );
  NAND2_X1 _208_ (
    .A1(a[7]),
    .A2(_080_),
    .ZN(_051_)
  );
  OAI221_X1 _209_ (
    .A(_051_),
    .B1(_048_),
    .B2(_083_),
    .C1(_063_),
    .C2(_084_),
    .ZN(_052_)
  );
  AOI211_X1 _210_ (
    .A(_050_),
    .B(_052_),
    .C1(adder_sum[7]),
    .C2(_078_),
    .ZN(_053_)
  );
  NOR2_X1 _211_ (
    .A1(rst),
    .A2(_053_),
    .ZN(_007_)
  );
  NAND4_X1 _212_ (
    .A1(_031_),
    .A2(_039_),
    .A3(_046_),
    .A4(_053_),
    .ZN(_054_)
  );
  NAND4_X1 _213_ (
    .A1(_087_),
    .A2(_095_),
    .A3(_013_),
    .A4(_022_),
    .ZN(_055_)
  );
  OAI21_X1 _214_ (
    .A(_070_),
    .B1(_054_),
    .B2(_055_),
    .ZN(_008_)
  );
  NAND3_X1 _215_ (
    .A1(_060_),
    .A2(carry_chain[8]),
    .A3(_075_),
    .ZN(_056_)
  );
  NOR2_X1 _216_ (
    .A1(_062_),
    .A2(_084_),
    .ZN(_057_)
  );
  AOI21_X1 _217_ (
    .A(_057_),
    .B1(sub_mode),
    .B2(_071_),
    .ZN(_058_)
  );
  OAI211_X1 _218_ (
    .A(_056_),
    .B(_058_),
    .C1(_069_),
    .C2(_082_),
    .ZN(_059_)
  );
  AND2_X1 _219_ (
    .A1(_070_),
    .A2(_059_),
    .ZN(_009_)
  );
  XOR2_X1 _220_ (
    .A(b[7]),
    .B(sub_mode),
    .Z(b_operand[7])
  );
  DFF_X1 _221_ (
    .CK(clk),
    .D(_006_),
    .Q(result[0]),
    .QN(_104_)
  );
  DFF_X1 _222_ (
    .CK(clk),
    .D(_005_),
    .Q(result[1]),
    .QN(_105_)
  );
  DFF_X1 _223_ (
    .CK(clk),
    .D(_004_),
    .Q(result[2]),
    .QN(_106_)
  );
  DFF_X1 _224_ (
    .CK(clk),
    .D(_003_),
    .Q(result[3]),
    .QN(_107_)
  );
  DFF_X1 _225_ (
    .CK(clk),
    .D(_002_),
    .Q(result[4]),
    .QN(_108_)
  );
  DFF_X1 _226_ (
    .CK(clk),
    .D(_001_),
    .Q(result[5]),
    .QN(_109_)
  );
  DFF_X1 _227_ (
    .CK(clk),
    .D(_000_),
    .Q(result[6]),
    .QN(_110_)
  );
  DFF_X1 _228_ (
    .CK(clk),
    .D(_007_),
    .Q(result[7]),
    .QN(_103_)
  );
  DFF_X1 _229_ (
    .CK(clk),
    .D(_008_),
    .Q(zero),
    .QN(_102_)
  );
  DFF_X1 _230_ (
    .CK(clk),
    .D(_009_),
    .Q(carry),
    .QN(_101_)
  );
  full_adder \ripple[0].fa  (
    .a(a[0]),
    .b(b_operand[0]),
    .cin(sub_mode),
    .cout(carry_chain[1]),
    .sum(adder_sum[0])
  );
  full_adder \ripple[1].fa  (
    .a(a[1]),
    .b(b_operand[1]),
    .cin(carry_chain[1]),
    .cout(carry_chain[2]),
    .sum(adder_sum[1])
  );
  full_adder \ripple[2].fa  (
    .a(a[2]),
    .b(b_operand[2]),
    .cin(carry_chain[2]),
    .cout(carry_chain[3]),
    .sum(adder_sum[2])
  );
  full_adder \ripple[3].fa  (
    .a(a[3]),
    .b(b_operand[3]),
    .cin(carry_chain[3]),
    .cout(carry_chain[4]),
    .sum(adder_sum[3])
  );
  full_adder \ripple[4].fa  (
    .a(a[4]),
    .b(b_operand[4]),
    .cin(carry_chain[4]),
    .cout(carry_chain[5]),
    .sum(adder_sum[4])
  );
  full_adder \ripple[5].fa  (
    .a(a[5]),
    .b(b_operand[5]),
    .cin(carry_chain[5]),
    .cout(carry_chain[6]),
    .sum(adder_sum[5])
  );
  full_adder \ripple[6].fa  (
    .a(a[6]),
    .b(b_operand[6]),
    .cin(carry_chain[6]),
    .cout(carry_chain[7]),
    .sum(adder_sum[6])
  );
  full_adder \ripple[7].fa  (
    .a(a[7]),
    .b(b_operand[7]),
    .cin(carry_chain[7]),
    .cout(carry_chain[8]),
    .sum(adder_sum[7])
  );
  assign carry_chain[0] = sub_mode;
endmodule

module full_adder(a, b, cin, sum, cout);
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output sum;
  wire sum;
  output cout;
  wire cout;
  wire _0_;
  wire _1_;
  wire _2_;
  INV_X1 _3_ (
    .A(cin),
    .ZN(_0_)
  );
  NAND2_X1 _4_ (
    .A1(a),
    .A2(b),
    .ZN(_1_)
  );
  XNOR2_X1 _5_ (
    .A(a),
    .B(b),
    .ZN(_2_)
  );
  XNOR2_X1 _6_ (
    .A(cin),
    .B(_2_),
    .ZN(sum)
  );
  OAI21_X1 _7_ (
    .A(_1_),
    .B1(_2_),
    .B2(_0_),
    .ZN(cout)
  );
endmodule
