/* Generated by Yosys 0.68+130 (git sha1 dd83bbad2-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module traffic_light(clk, rst, red, green, yellow);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output red;
  wire red;
  output green;
  wire green;
  output yellow;
  wire yellow;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire [2:0] state;
  NOR4_X1 _06_ (
    .A1(_00_),
    .A2(state[1]),
    .A3(state[2]),
    .A4(rst),
    .ZN(_02_)
  );
  NOR4_X1 _07_ (
    .A1(state[0]),
    .A2(_01_),
    .A3(state[2]),
    .A4(rst),
    .ZN(_04_)
  );
  NOR2_X1 _08_ (
    .A1(_02_),
    .A2(_04_),
    .ZN(_03_)
  );
  DFF_X1 _09_ (
    .CK(clk),
    .D(_04_),
    .Q(state[2]),
    .QN(_05_)
  );
  DFF_X1 _10_ (
    .CK(clk),
    .D(_02_),
    .Q(state[1]),
    .QN(_01_)
  );
  DFF_X1 _11_ (
    .CK(clk),
    .D(_03_),
    .Q(state[0]),
    .QN(_00_)
  );
  assign yellow = state[2];
  assign green = state[1];
  assign red = state[0];
endmodule
