/* Generated by Yosys 0.68+195 (git sha1 435977e97-dirty, Release, Clang /usr/bin/clang++ 21.1.8) */

module gate(clk, rst, red, green, yellow);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output red;
  wire red;
  output green;
  wire green;
  output yellow;
  wire yellow;
  wire [2:0] _00_;
  wire _01_;
  wire _02_;
  wire [2:0] _03_;
  wire _04_;
  wire [2:0] _05_;
  reg [2:0] state;
  always @(posedge clk)
    state <= _03_;
  assign _01_ = state == 3'h2;
  assign _02_ = state == 3'h1;
  assign _03_ = _04_ ? 3'h1 : _05_;
  function [2:0] _10_;
    input [2:0] a;
    input [5:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _10_ = b[2:0];
      2'b1?:
        _10_ = b[5:3];
      default:
        _10_ = a;
    endcase
  endfunction
  assign _05_ = _10_(3'h1, 6'h14, { _02_, _01_ });
  assign red = state[0];
  assign green = state[1];
  assign yellow = state[2];
  assign _04_ = rst;
  assign _00_ = _03_;
endmodule

module gold(clk, rst, red, green, yellow);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output red;
  wire red;
  output green;
  wire green;
  output yellow;
  wire yellow;
  wire _00_;
  wire _01_;
  wire [1:0] _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire [1:0] _07_;
  wire _08_;
  wire _09_;
  wire [1:0] _10_;
  wire _11_;
  reg [1:0] state;
  assign _04_ = ! state;
  assign _05_ = state == 2'h1;
  assign _06_ = state == 2'h2;
  always @(posedge clk)
    state <= _10_;
  function [1:0] _16_;
    input [1:0] a;
    input [3:0] b;
    input [1:0] s;
    casez (s) // synopsys parallel_case
      2'b?1:
        _16_ = b[1:0];
      2'b1?:
        _16_ = b[3:2];
      default:
        _16_ = a;
    endcase
  endfunction
  assign _07_ = _16_(2'h0, 4'h6, { _09_, _08_ });
  assign _08_ = state == 2'h1;
  assign _09_ = ! state;
  assign _10_ = _11_ ? 2'h0 : _07_;
  assign _03_ = _06_;
  assign _00_ = _05_;
  assign _01_ = _04_;
  assign _11_ = rst;
  assign _02_ = _10_;
  assign red = _04_;
  assign green = _05_;
  assign yellow = _06_;
endmodule
