/* Generated by Yosys 0.68+130 (git sha1 dd83bbad2-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module gate(clk, rst, in_valid, ar, ai, br, bi, out_valid, cr, ci);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input in_valid;
  wire in_valid;
  input signed [7:0] ar;
  wire signed [7:0] ar;
  input signed [7:0] ai;
  wire signed [7:0] ai;
  input signed [7:0] br;
  wire signed [7:0] br;
  input signed [7:0] bi;
  wire signed [7:0] bi;
  output out_valid;
  reg out_valid;
  output signed [19:0] cr;
  reg signed [19:0] cr;
  output signed [19:0] ci;
  reg signed [19:0] ci;
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire [19:0] _04_;
  wire [19:0] _05_;
  wire [15:0] _06_;
  wire [15:0] _07_;
  wire _08_;
  wire [15:0] _09_;
  wire [15:0] _10_;
  wire _11_;
  wire _12_;
  wire [19:0] _13_;
  wire [19:0] _14_;
  wire [19:0] _15_;
  wire [19:0] _16_;
  reg signed [7:0] ai_r;
  reg signed [7:0] ar_r;
  reg signed [7:0] bi_r;
  reg signed [7:0] br_r;
  wire signed [15:0] ii;
  reg signed [15:0] ii_r;
  wire signed [16:0] imag_part;
  wire signed [15:0] ir;
  reg signed [15:0] ir_r;
  wire signed [16:0] real_part;
  wire signed [15:0] ri;
  reg signed [15:0] ri_r;
  wire signed [15:0] rr;
  reg signed [15:0] rr_r;
  reg vld;
  reg vld2;
  assign imag_part = $signed(ri_r) + $signed(ir_r);
  assign _13_ = cr + { real_part[16], real_part[16], real_part[16], real_part };
  assign _14_ = ci + { imag_part[16], imag_part[16], imag_part[16], imag_part };
  assign rr = $signed(ar_r) * $signed(br_r);
  assign ii = $signed(ai_r) * $signed(bi_r);
  assign ri = $signed(ar_r) * $signed(bi_r);
  assign ir = $signed(ai_r) * $signed(br_r);
  always @(posedge clk)
    out_valid <= _08_;
  always @(posedge clk)
    cr <= _05_;
  always @(posedge clk)
    ci <= _04_;
  always @(posedge clk)
    vld2 <= _11_;
  always @(posedge clk)
    ir_r <= _07_;
  always @(posedge clk)
    ri_r <= _09_;
  always @(posedge clk)
    ii_r <= _06_;
  always @(posedge clk)
    rr_r <= _10_;
  always @(posedge clk)
    ar_r <= _01_;
  always @(posedge clk)
    ai_r <= _00_;
  always @(posedge clk)
    br_r <= _03_;
  always @(posedge clk)
    bi_r <= _02_;
  always @(posedge clk)
    vld <= _12_;
  assign _08_ = rst ? 1'h0 : vld2;
  assign _15_ = vld2 ? _14_ : ci;
  assign _04_ = rst ? 20'h00000 : _15_;
  assign _16_ = vld2 ? _13_ : cr;
  assign _05_ = rst ? 20'h00000 : _16_;
  assign _11_ = rst ? 1'h0 : vld;
  assign _07_ = rst ? 16'h0000 : ir;
  assign _09_ = rst ? 16'h0000 : ri;
  assign _06_ = rst ? 16'h0000 : ii;
  assign _10_ = rst ? 16'h0000 : rr;
  assign _12_ = rst ? 1'h0 : in_valid;
  assign _02_ = rst ? 8'h00 : bi;
  assign _03_ = rst ? 8'h00 : br;
  assign _00_ = rst ? 8'h00 : ai;
  assign _01_ = rst ? 8'h00 : ar;
  assign real_part = $signed(rr_r) - $signed(ii_r);
endmodule

module gold(clk, rst, in_valid, ar, ai, br, bi, out_valid, cr, ci);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input in_valid;
  wire in_valid;
  input signed [7:0] ar;
  wire signed [7:0] ar;
  input signed [7:0] ai;
  wire signed [7:0] ai;
  input signed [7:0] br;
  wire signed [7:0] br;
  input signed [7:0] bi;
  wire signed [7:0] bi;
  output out_valid;
  reg out_valid;
  output signed [19:0] cr;
  reg signed [19:0] cr;
  output signed [19:0] ci;
  reg signed [19:0] ci;
  wire [7:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire [19:0] _04_;
  wire [19:0] _05_;
  wire _06_;
  wire _07_;
  wire [19:0] _08_;
  wire [19:0] _09_;
  wire [19:0] _10_;
  wire [19:0] _11_;
  reg signed [7:0] ai_r;
  reg signed [7:0] ar_r;
  reg signed [7:0] bi_r;
  reg signed [7:0] br_r;
  wire signed [15:0] ii;
  wire signed [16:0] imag_part;
  wire signed [15:0] ir;
  wire signed [16:0] real_part;
  wire signed [15:0] ri;
  wire signed [15:0] rr;
  reg vld;
  assign imag_part = $signed(ri) + $signed(ir);
  assign _08_ = cr + { real_part[16], real_part[16], real_part[16], real_part };
  assign _09_ = ci + { imag_part[16], imag_part[16], imag_part[16], imag_part };
  assign rr = $signed(ar_r) * $signed(br_r);
  assign ii = $signed(ai_r) * $signed(bi_r);
  assign ri = $signed(ar_r) * $signed(bi_r);
  assign ir = $signed(ai_r) * $signed(br_r);
  always @(posedge clk)
    out_valid <= _06_;
  always @(posedge clk)
    cr <= _05_;
  always @(posedge clk)
    ci <= _04_;
  always @(posedge clk)
    ar_r <= _01_;
  always @(posedge clk)
    ai_r <= _00_;
  always @(posedge clk)
    br_r <= _03_;
  always @(posedge clk)
    bi_r <= _02_;
  always @(posedge clk)
    vld <= _07_;
  assign _06_ = rst ? 1'h0 : vld;
  assign _10_ = vld ? _09_ : ci;
  assign _04_ = rst ? 20'h00000 : _10_;
  assign _11_ = vld ? _08_ : cr;
  assign _05_ = rst ? 20'h00000 : _11_;
  assign _07_ = rst ? 1'h0 : in_valid;
  assign _02_ = rst ? 8'h00 : bi;
  assign _03_ = rst ? 8'h00 : br;
  assign _00_ = rst ? 8'h00 : ai;
  assign _01_ = rst ? 8'h00 : ar;
  assign real_part = $signed(rr) - $signed(ii);
endmodule
