/* Generated by Yosys 0.68+195 (git sha1 435977e97-dirty, Release, Clang /usr/bin/clang++ 21.1.8) */

module gate(clk, rst, in_valid, a_vec, b_vec, out_valid, acc);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input in_valid;
  wire in_valid;
  input [31:0] a_vec;
  wire [31:0] a_vec;
  input [31:0] b_vec;
  wire [31:0] b_vec;
  output out_valid;
  reg out_valid;
  output signed [19:0] acc;
  reg signed [19:0] acc;
  wire [31:0] _00_;
  wire [19:0] _01_;
  wire [31:0] _02_;
  wire _03_;
  wire [16:0] _04_;
  wire _05_;
  wire _06_;
  wire [19:0] _07_;
  wire [19:0] _08_;
  wire signed [7:0] a0;
  wire signed [7:0] a1;
  wire signed [7:0] a2;
  wire signed [7:0] a3;
  reg [31:0] a_reg;
  wire signed [7:0] b0;
  wire signed [7:0] b1;
  wire signed [7:0] b2;
  wire signed [7:0] b3;
  reg [31:0] b_reg;
  wire signed [16:0] h0;
  wire signed [16:0] h1;
  wire signed [15:0] m0;
  wire signed [15:0] m1;
  wire signed [15:0] m2;
  wire signed [15:0] m3;
  wire signed [17:0] sum;
  reg signed [16:0] sum_reg;
  reg vld;
  reg vld2;
  assign h0 = $signed(m0) + $signed(m1);
  assign h1 = $signed(m2) + $signed(m3);
  assign sum = $signed(h0) + $signed(h1);
  assign _07_ = acc + { 1'h0, sum_reg[16], sum_reg[16], sum_reg };
  assign m0 = $signed(a_reg[7:0]) * $signed(b_reg[7:0]);
  assign m1 = $signed(a_reg[15:8]) * $signed(b_reg[15:8]);
  assign m2 = $signed(a_reg[23:16]) * $signed(b_reg[23:16]);
  assign m3 = $signed(a_reg[31:24]) * $signed(b_reg[31:24]);
  always @(posedge clk)
    acc <= _01_;
  always @(posedge clk)
    out_valid <= _03_;
  always @(posedge clk)
    vld2 <= _05_;
  always @(posedge clk)
    sum_reg <= _04_;
  always @(posedge clk)
    a_reg <= _00_;
  always @(posedge clk)
    b_reg <= _02_;
  always @(posedge clk)
    vld <= _06_;
  assign _03_ = rst ? 1'h0 : vld2;
  assign _08_ = vld2 ? _07_ : acc;
  assign _01_ = rst ? 20'h00000 : _08_;
  assign _05_ = rst ? 1'h0 : vld;
  assign _04_ = rst ? 17'h00000 : sum[16:0];
  assign _06_ = rst ? 1'h0 : in_valid;
  assign _02_ = rst ? 32'd0 : b_vec;
  assign _00_ = rst ? 32'd0 : a_vec;
  assign b3 = b_reg[31:24];
  assign b2 = b_reg[23:16];
  assign b1 = b_reg[15:8];
  assign b0 = b_reg[7:0];
  assign a3 = a_reg[31:24];
  assign a2 = a_reg[23:16];
  assign a1 = a_reg[15:8];
  assign a0 = a_reg[7:0];
endmodule

module gold(clk, rst, in_valid, a_vec, b_vec, out_valid, acc);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input in_valid;
  wire in_valid;
  input [31:0] a_vec;
  wire [31:0] a_vec;
  input [31:0] b_vec;
  wire [31:0] b_vec;
  output out_valid;
  reg out_valid;
  output signed [19:0] acc;
  reg signed [19:0] acc;
  wire [31:0] _00_;
  wire [19:0] _01_;
  wire [31:0] _02_;
  wire _03_;
  wire _04_;
  wire [19:0] _05_;
  wire [19:0] _06_;
  wire signed [7:0] a0;
  wire signed [7:0] a1;
  wire signed [7:0] a2;
  wire signed [7:0] a3;
  reg [31:0] a_reg;
  wire signed [7:0] b0;
  wire signed [7:0] b1;
  wire signed [7:0] b2;
  wire signed [7:0] b3;
  reg [31:0] b_reg;
  wire signed [16:0] h0;
  wire signed [16:0] h1;
  wire signed [15:0] m0;
  wire signed [15:0] m1;
  wire signed [15:0] m2;
  wire signed [15:0] m3;
  wire signed [17:0] sum;
  reg vld;
  assign h0 = $signed(m0) + $signed(m1);
  assign h1 = $signed(m2) + $signed(m3);
  assign sum = $signed(h0) + $signed(h1);
  assign _05_ = acc + { sum[17], sum[17], sum };
  assign m0 = $signed(a_reg[7:0]) * $signed(b_reg[7:0]);
  assign m1 = $signed(a_reg[15:8]) * $signed(b_reg[15:8]);
  assign m2 = $signed(a_reg[23:16]) * $signed(b_reg[23:16]);
  assign m3 = $signed(a_reg[31:24]) * $signed(b_reg[31:24]);
  always @(posedge clk)
    acc <= _01_;
  always @(posedge clk)
    out_valid <= _03_;
  always @(posedge clk)
    a_reg <= _00_;
  always @(posedge clk)
    b_reg <= _02_;
  always @(posedge clk)
    vld <= _04_;
  assign _03_ = rst ? 1'h0 : vld;
  assign _06_ = vld ? _05_ : acc;
  assign _01_ = rst ? 20'h00000 : _06_;
  assign _04_ = rst ? 1'h0 : in_valid;
  assign _02_ = rst ? 32'd0 : b_vec;
  assign _00_ = rst ? 32'd0 : a_vec;
  assign b3 = b_reg[31:24];
  assign b2 = b_reg[23:16];
  assign b1 = b_reg[15:8];
  assign b0 = b_reg[7:0];
  assign a3 = a_reg[31:24];
  assign a2 = a_reg[23:16];
  assign a1 = a_reg[15:8];
  assign a0 = a_reg[7:0];
endmodule
