/* Generated by Yosys 0.68+130 (git sha1 dd83bbad2-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin25.5-clang++ 21.1.8) */

module gate(clk, rst, count);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [7:0] count;
  reg [7:0] count;
  wire [7:0] _0_;
  wire [7:0] _1_;
  wire [7:0] _2_;
  wire _3_;
  assign _1_ = count + 1'h1;
  always @(posedge clk)
    count <= _2_;
  assign _2_ = _3_ ? 8'h01 : _1_;
  assign _3_ = rst;
  assign _0_ = _2_;
endmodule

module gold(clk, rst, count);
  input clk;
  wire clk;
  input rst;
  wire rst;
  output [7:0] count;
  reg [7:0] count;
  wire [7:0] _0_;
  wire [7:0] _1_;
  wire _2_;
  wire [7:0] _3_;
  assign _1_ = count + 1'h1;
  always @(posedge clk)
    count <= _3_;
  assign _3_ = _2_ ? 8'h00 : _1_;
  assign _2_ = rst;
  assign _0_ = _3_;
endmodule
