/* Generated by Yosys 0.33 (git sha1 2584903a060) */

module gate(clk, rst, in_valid, a_vec, b_vec, out_valid, acc);
  wire [63:0] _00_;
  wire [20:0] _01_;
  wire [63:0] _02_;
  wire _03_;
  wire _04_;
  reg [63:0] a_reg;
  input [63:0] a_vec;
  wire [63:0] a_vec;
  output [20:0] acc;
  reg [20:0] acc;
  reg [63:0] b_reg;
  input [63:0] b_vec;
  wire [63:0] b_vec;
  input clk;
  wire clk;
  input in_valid;
  wire in_valid;
  wire [15:0] m0;
  wire [15:0] m1;
  wire [15:0] m2;
  wire [15:0] m3;
  wire [15:0] m4;
  wire [15:0] m5;
  wire [15:0] m6;
  wire [15:0] m7;
  output out_valid;
  reg out_valid;
  input rst;
  wire rst;
  wire [20:0] sum;
  wire [20:0] t0;
  wire [20:0] t1;
  wire [20:0] t2;
  wire [20:0] t3;
  wire [20:0] u0;
  wire [20:0] u1;
  reg vld;
  assign t0 = m0 + m1;
  assign t1 = m2 + m3;
  assign t2 = m4 + m5;
  assign t3 = m6 + m7;
  assign u0 = t0 + t1;
  assign u1 = t2 + t3;
  assign sum = u0 + u1;
  assign m0 = a_reg[7:0] * b_reg[7:0];
  assign m1 = a_reg[15:8] * b_reg[15:8];
  assign m2 = a_reg[23:16] * b_reg[23:16];
  assign m3 = a_reg[31:24] * b_reg[31:24];
  assign m4 = a_reg[39:32] * b_reg[39:32];
  assign m5 = a_reg[47:40] * b_reg[47:40];
  assign m6 = a_reg[55:48] * b_reg[55:48];
  assign m7 = a_reg[63:56] * b_reg[63:56];
  always @(posedge clk)
    out_valid <= _03_;
  always @(posedge clk)
    acc <= _01_;
  always @(posedge clk)
    a_reg <= _00_;
  always @(posedge clk)
    b_reg <= _02_;
  always @(posedge clk)
    vld <= _04_;
  assign _03_ = rst ? 1'h0 : vld;
  assign _01_ = rst ? 21'h000000 : sum;
  assign _04_ = rst ? 1'h0 : in_valid;
  assign _02_ = rst ? 64'h0000000000000000 : b_vec;
  assign _00_ = rst ? 64'h0000000000000000 : a_vec;
endmodule

module gold(clk, rst, in_valid, a_vec, b_vec, out_valid, acc);
  wire [63:0] _00_;
  wire [20:0] _01_;
  wire [63:0] _02_;
  wire _03_;
  wire _04_;
  reg [63:0] a_reg;
  input [63:0] a_vec;
  wire [63:0] a_vec;
  output [20:0] acc;
  reg [20:0] acc;
  reg [63:0] b_reg;
  input [63:0] b_vec;
  wire [63:0] b_vec;
  wire [20:0] c0;
  wire [20:0] c1;
  wire [20:0] c2;
  wire [20:0] c3;
  wire [20:0] c4;
  wire [20:0] c5;
  wire [20:0] c6;
  wire [20:0] c7;
  input clk;
  wire clk;
  input in_valid;
  wire in_valid;
  wire [15:0] m0;
  wire [15:0] m1;
  wire [15:0] m2;
  wire [15:0] m3;
  wire [15:0] m4;
  wire [15:0] m5;
  wire [15:0] m6;
  wire [15:0] m7;
  output out_valid;
  reg out_valid;
  input rst;
  wire rst;
  reg vld;
  assign c1 = { 5'h00, m0 } + m1;
  assign c2 = c1 + m2;
  assign c3 = c2 + m3;
  assign c4 = c3 + m4;
  assign c5 = c4 + m5;
  assign c6 = c5 + m6;
  assign c7 = c6 + m7;
  assign m0 = a_reg[7:0] * b_reg[7:0];
  assign m1 = a_reg[15:8] * b_reg[15:8];
  assign m2 = a_reg[23:16] * b_reg[23:16];
  assign m3 = a_reg[31:24] * b_reg[31:24];
  assign m4 = a_reg[39:32] * b_reg[39:32];
  assign m5 = a_reg[47:40] * b_reg[47:40];
  assign m6 = a_reg[55:48] * b_reg[55:48];
  assign m7 = a_reg[63:56] * b_reg[63:56];
  always @(posedge clk)
    out_valid <= _03_;
  always @(posedge clk)
    acc <= _01_;
  always @(posedge clk)
    a_reg <= _00_;
  always @(posedge clk)
    b_reg <= _02_;
  always @(posedge clk)
    vld <= _04_;
  assign _03_ = rst ? 1'h0 : vld;
  assign _01_ = rst ? 21'h000000 : c7;
  assign _04_ = rst ? 1'h0 : in_valid;
  assign _02_ = rst ? 64'h0000000000000000 : b_vec;
  assign _00_ = rst ? 64'h0000000000000000 : a_vec;
  assign c0 = { 5'h00, m0 };
endmodule
